// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package storepg

import (
	"context"
	"time"
)

const countApplicationLogs = `-- name: CountApplicationLogs :one
SELECT count(*) FROM application_logs
WHERE ($1::text IS NULL OR level = $1::text)
  AND ($2::text IS NULL OR component = $2::text)
  AND ($3::bigint IS NULL OR server_id = $3::bigint)
  AND ($4::text IS NULL OR request_id = $4::text)
  AND ($5::text IS NULL OR message ILIKE '%' || $5::text || '%')
  AND ($6::timestamptz IS NULL OR ts >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR ts <= $7::timestamptz)
`

type CountApplicationLogsParams struct {
	Level     *string    `json:"level"`
	Component *string    `json:"component"`
	ServerID  *int64     `json:"server_id"`
	RequestID *string    `json:"request_id"`
	Search    *string    `json:"search"`
	FromTs    *time.Time `json:"from_ts"`
	ToTs      *time.Time `json:"to_ts"`
}

func (q *Queries) CountApplicationLogs(ctx context.Context, arg CountApplicationLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationLogs,
		arg.Level,
		arg.Component,
		arg.ServerID,
		arg.RequestID,
		arg.Search,
		arg.FromTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditByAction = `-- name: CountAuditByAction :many
SELECT action, count(*) AS count FROM audit_logs
WHERE ts > $1 GROUP BY action ORDER BY count DESC
`

type CountAuditByActionRow struct {
	Action string `json:"action"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountAuditByAction(ctx context.Context, ts time.Time) ([]CountAuditByActionRow, error) {
	rows, err := q.db.Query(ctx, countAuditByAction, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAuditByActionRow{}
	for rows.Next() {
		var i CountAuditByActionRow
		if err := rows.Scan(&i.Action, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditByResult = `-- name: CountAuditByResult :many
SELECT result, count(*) AS count FROM audit_logs
WHERE ts > $1 GROUP BY result ORDER BY count DESC
`

type CountAuditByResultRow struct {
	Result string `json:"result"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountAuditByResult(ctx context.Context, ts time.Time) ([]CountAuditByResultRow, error) {
	rows, err := q.db.Query(ctx, countAuditByResult, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAuditByResultRow{}
	for rows.Next() {
		var i CountAuditByResultRow
		if err := rows.Scan(&i.Result, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs
WHERE ($1::bigint IS NULL OR actor_id = $1::bigint)
  AND ($2::bigint IS NULL OR server_id = $2::bigint)
  AND ($3::text IS NULL OR action = $3::text)
  AND ($4::text IS NULL OR result = $4::text)
  AND ($5::text IS NULL OR ip = $5::text)
  AND ($6::text IS NULL OR request_id = $6::text)
  AND ($7::timestamptz IS NULL OR ts >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR ts <= $8::timestamptz)
  AND ($9::text IS NULL
       OR action ILIKE '%' || $9::text || '%'
       OR target ILIKE '%' || $9::text || '%'
       OR actor_name ILIKE '%' || $9::text || '%'
       OR server_name ILIKE '%' || $9::text || '%')
`

type CountAuditLogsParams struct {
	ActorID   *int64     `json:"actor_id"`
	ServerID  *int64     `json:"server_id"`
	Action    *string    `json:"action"`
	Result    *string    `json:"result"`
	Ip        *string    `json:"ip"`
	RequestID *string    `json:"request_id"`
	FromTs    *time.Time `json:"from_ts"`
	ToTs      *time.Time `json:"to_ts"`
	Search    *string    `json:"search"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.ActorID,
		arg.ServerID,
		arg.Action,
		arg.Result,
		arg.Ip,
		arg.RequestID,
		arg.FromTs,
		arg.ToTs,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSecurityEvents = `-- name: CountSecurityEvents :one
SELECT count(*) FROM audit_logs
WHERE ts > $1 AND action IN ('SECURITY_EVENT', 'ACCESS_DENIED', 'LOGIN_FAILED')
`

func (q *Queries) CountSecurityEvents(ctx context.Context, ts time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countSecurityEvents, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteApplicationLogsBefore = `-- name: DeleteApplicationLogsBefore :execrows
DELETE FROM application_logs WHERE ts < $1
`

func (q *Queries) DeleteApplicationLogsBefore(ctx context.Context, ts time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApplicationLogsBefore, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAuditBefore = `-- name: DeleteAuditBefore :execrows
DELETE FROM audit_logs WHERE ts < $1
`

// The single permitted deletion path. The caller records an AUDIT_PRUNED
// event so that pruning is itself visible in the trail.
func (q *Queries) DeleteAuditBefore(ctx context.Context, ts time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuditBefore, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT id, ts, actor_id, actor_name, action, target, server_id, server_name, result, request_id, ip, user_agent, metadata FROM audit_logs WHERE id = $1
`

func (q *Queries) GetAuditLog(ctx context.Context, id int64) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLog, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.ActorID,
		&i.ActorName,
		&i.Action,
		&i.Target,
		&i.ServerID,
		&i.ServerName,
		&i.Result,
		&i.RequestID,
		&i.Ip,
		&i.UserAgent,
		&i.Metadata,
	)
	return i, err
}

const insertApplicationLog = `-- name: InsertApplicationLog :one

INSERT INTO application_logs (level, component, message, request_id, actor_id, server_id, fields)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, ts, level, component, message, request_id, actor_id, server_id, fields
`

type InsertApplicationLogParams struct {
	Level     string `json:"level"`
	Component string `json:"component"`
	Message   string `json:"message"`
	RequestID string `json:"request_id"`
	ActorID   *int64 `json:"actor_id"`
	ServerID  *int64 `json:"server_id"`
	Fields    []byte `json:"fields"`
}

// Application logs ------------------------------------------------------------
func (q *Queries) InsertApplicationLog(ctx context.Context, arg InsertApplicationLogParams) (ApplicationLog, error) {
	row := q.db.QueryRow(ctx, insertApplicationLog,
		arg.Level,
		arg.Component,
		arg.Message,
		arg.RequestID,
		arg.ActorID,
		arg.ServerID,
		arg.Fields,
	)
	var i ApplicationLog
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.Level,
		&i.Component,
		&i.Message,
		&i.RequestID,
		&i.ActorID,
		&i.ServerID,
		&i.Fields,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one

INSERT INTO audit_logs (actor_id, actor_name, action, target, server_id, server_name,
                        result, request_id, ip, user_agent, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, ts, actor_id, actor_name, action, target, server_id, server_name, result, request_id, ip, user_agent, metadata
`

type InsertAuditLogParams struct {
	ActorID    *int64 `json:"actor_id"`
	ActorName  string `json:"actor_name"`
	Action     string `json:"action"`
	Target     string `json:"target"`
	ServerID   *int64 `json:"server_id"`
	ServerName string `json:"server_name"`
	Result     string `json:"result"`
	RequestID  string `json:"request_id"`
	Ip         string `json:"ip"`
	UserAgent  string `json:"user_agent"`
	Metadata   []byte `json:"metadata"`
}

// Audit log -----------------------------------------------------------------
//
// append-only: these queries only ever INSERT or SELECT. No UPDATE or DELETE
// query exists, which is what makes the trail tamper-resistant through the
// application (Design Spec §27.1). Retention pruning runs through
// DeleteAuditBefore, the single documented exception.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ActorID,
		arg.ActorName,
		arg.Action,
		arg.Target,
		arg.ServerID,
		arg.ServerName,
		arg.Result,
		arg.RequestID,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.ActorID,
		&i.ActorName,
		&i.Action,
		&i.Target,
		&i.ServerID,
		&i.ServerName,
		&i.Result,
		&i.RequestID,
		&i.Ip,
		&i.UserAgent,
		&i.Metadata,
	)
	return i, err
}

const listApplicationLogs = `-- name: ListApplicationLogs :many
SELECT id, ts, level, component, message, request_id, actor_id, server_id, fields FROM application_logs
WHERE ($3::text IS NULL OR level = $3::text)
  AND ($4::text IS NULL OR component = $4::text)
  AND ($5::bigint IS NULL OR server_id = $5::bigint)
  AND ($6::text IS NULL OR request_id = $6::text)
  AND ($7::text IS NULL OR message ILIKE '%' || $7::text || '%')
  AND ($8::timestamptz IS NULL OR ts >= $8::timestamptz)
  AND ($9::timestamptz IS NULL OR ts <= $9::timestamptz)
ORDER BY ts DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListApplicationLogsParams struct {
	Limit     int32      `json:"limit"`
	Offset    int32      `json:"offset"`
	Level     *string    `json:"level"`
	Component *string    `json:"component"`
	ServerID  *int64     `json:"server_id"`
	RequestID *string    `json:"request_id"`
	Search    *string    `json:"search"`
	FromTs    *time.Time `json:"from_ts"`
	ToTs      *time.Time `json:"to_ts"`
}

func (q *Queries) ListApplicationLogs(ctx context.Context, arg ListApplicationLogsParams) ([]ApplicationLog, error) {
	rows, err := q.db.Query(ctx, listApplicationLogs,
		arg.Limit,
		arg.Offset,
		arg.Level,
		arg.Component,
		arg.ServerID,
		arg.RequestID,
		arg.Search,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationLog{}
	for rows.Next() {
		var i ApplicationLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Level,
			&i.Component,
			&i.Message,
			&i.RequestID,
			&i.ActorID,
			&i.ServerID,
			&i.Fields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, ts, actor_id, actor_name, action, target, server_id, server_name, result, request_id, ip, user_agent, metadata FROM audit_logs
WHERE ($3::bigint IS NULL OR actor_id = $3::bigint)
  AND ($4::bigint IS NULL OR server_id = $4::bigint)
  AND ($5::text IS NULL OR action = $5::text)
  AND ($6::text IS NULL OR result = $6::text)
  AND ($7::text IS NULL OR ip = $7::text)
  AND ($8::text IS NULL OR request_id = $8::text)
  AND ($9::timestamptz IS NULL OR ts >= $9::timestamptz)
  AND ($10::timestamptz IS NULL OR ts <= $10::timestamptz)
  AND ($11::text IS NULL
       OR action ILIKE '%' || $11::text || '%'
       OR target ILIKE '%' || $11::text || '%'
       OR actor_name ILIKE '%' || $11::text || '%'
       OR server_name ILIKE '%' || $11::text || '%')
ORDER BY ts DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit     int32      `json:"limit"`
	Offset    int32      `json:"offset"`
	ActorID   *int64     `json:"actor_id"`
	ServerID  *int64     `json:"server_id"`
	Action    *string    `json:"action"`
	Result    *string    `json:"result"`
	Ip        *string    `json:"ip"`
	RequestID *string    `json:"request_id"`
	FromTs    *time.Time `json:"from_ts"`
	ToTs      *time.Time `json:"to_ts"`
	Search    *string    `json:"search"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.ActorID,
		arg.ServerID,
		arg.Action,
		arg.Result,
		arg.Ip,
		arg.RequestID,
		arg.FromTs,
		arg.ToTs,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.Target,
			&i.ServerID,
			&i.ServerName,
			&i.Result,
			&i.RequestID,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAuditForServer = `-- name: ListRecentAuditForServer :many
SELECT id, ts, actor_id, actor_name, action, target, server_id, server_name, result, request_id, ip, user_agent, metadata FROM audit_logs WHERE server_id = $1 ORDER BY ts DESC, id DESC LIMIT $2
`

type ListRecentAuditForServerParams struct {
	ServerID *int64 `json:"server_id"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) ListRecentAuditForServer(ctx context.Context, arg ListRecentAuditForServerParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listRecentAuditForServer, arg.ServerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.Target,
			&i.ServerID,
			&i.ServerName,
			&i.Result,
			&i.RequestID,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
