// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package storepg

import (
	"context"
	"time"
)

const cancelJob = `-- name: CancelJob :exec
UPDATE jobs
SET status = 'cancelled', finished_at = now(), updated_at = now(),
    locked_by = NULL, locked_at = NULL
WHERE id = $1 AND status IN ('queued', 'retrying', 'running')
`

func (q *Queries) CancelJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, cancelJob, id)
	return err
}

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET status     = 'running',
    locked_by  = $1,
    locked_at  = now(),
    attempts   = attempts + 1,
    updated_at = now()
WHERE id = (
    SELECT id FROM jobs
    WHERE status = 'queued' AND run_at <= now()
    ORDER BY priority DESC, id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, kind, status, priority, attempts, max_attempts, run_at, locked_by, locked_at, payload, progress, last_error, created_by, server_id, created_at, updated_at, finished_at, dedupe_key
`

func (q *Queries) ClaimJob(ctx context.Context, lockedBy *string) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, lockedBy)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.Payload,
		&i.Progress,
		&i.LastError,
		&i.CreatedBy,
		&i.ServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DedupeKey,
	)
	return i, err
}

const claimJobByKind = `-- name: ClaimJobByKind :one
UPDATE jobs
SET status     = 'running',
    locked_by  = $1,
    locked_at  = now(),
    attempts   = attempts + 1,
    updated_at = now()
WHERE id = (
    SELECT id FROM jobs
    WHERE jobs.status = 'queued' AND jobs.run_at <= now() AND jobs.kind = $2
    ORDER BY priority DESC, id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, kind, status, priority, attempts, max_attempts, run_at, locked_by, locked_at, payload, progress, last_error, created_by, server_id, created_at, updated_at, finished_at, dedupe_key
`

type ClaimJobByKindParams struct {
	LockedBy *string `json:"locked_by"`
	Kind     string  `json:"kind"`
}

func (q *Queries) ClaimJobByKind(ctx context.Context, arg ClaimJobByKindParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimJobByKind, arg.LockedBy, arg.Kind)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.Payload,
		&i.Progress,
		&i.LastError,
		&i.CreatedBy,
		&i.ServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DedupeKey,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs
SET status = 'succeeded', progress = 1, finished_at = now(), updated_at = now(),
    locked_by = NULL, locked_at = NULL
WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const countJobs = `-- name: CountJobs :one
SELECT count(*) FROM jobs
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR kind = $2::text)
  AND ($3::bigint IS NULL OR server_id = $3::bigint)
  AND ($4::bigint IS NULL OR created_by = $4::bigint)
`

type CountJobsParams struct {
	Status    *string `json:"status"`
	Kind      *string `json:"kind"`
	ServerID  *int64  `json:"server_id"`
	CreatedBy *int64  `json:"created_by"`
}

func (q *Queries) CountJobs(ctx context.Context, arg CountJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs,
		arg.Status,
		arg.Kind,
		arg.ServerID,
		arg.CreatedBy,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobsByStatus = `-- name: CountJobsByStatus :many
SELECT status, count(*) AS count FROM jobs GROUP BY status
`

type CountJobsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountJobsByStatus(ctx context.Context) ([]CountJobsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByStatusRow{}
	for rows.Next() {
		var i CountJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingJobs = `-- name: CountPendingJobs :one
SELECT count(*) FROM jobs WHERE status IN ('queued', 'retrying')
`

func (q *Queries) CountPendingJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunningJobs = `-- name: CountRunningJobs :one
SELECT count(*) FROM jobs WHERE status = 'running'
`

func (q *Queries) CountRunningJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deadJob = `-- name: DeadJob :exec
UPDATE jobs
SET status      = 'dead',
    last_error  = $2,
    finished_at = now(),
    updated_at  = now(),
    locked_by   = NULL,
    locked_at   = NULL
WHERE id = $1
`

type DeadJobParams struct {
	ID        int64  `json:"id"`
	LastError string `json:"last_error"`
}

// Terminal failure: attempts exhausted.
func (q *Queries) DeadJob(ctx context.Context, arg DeadJobParams) error {
	_, err := q.db.Exec(ctx, deadJob, arg.ID, arg.LastError)
	return err
}

const deleteFinishedJobsBefore = `-- name: DeleteFinishedJobsBefore :execrows
DELETE FROM jobs
WHERE status IN ('succeeded', 'dead', 'cancelled') AND finished_at IS NOT NULL AND finished_at < $1
`

func (q *Queries) DeleteFinishedJobsBefore(ctx context.Context, finishedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedJobsBefore, finishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueJob = `-- name: EnqueueJob :one

INSERT INTO jobs (kind, priority, max_attempts, run_at, payload, created_by, server_id, dedupe_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, kind, status, priority, attempts, max_attempts, run_at, locked_by, locked_at, payload, progress, last_error, created_by, server_id, created_at, updated_at, finished_at, dedupe_key
`

type EnqueueJobParams struct {
	Kind        string    `json:"kind"`
	Priority    int32     `json:"priority"`
	MaxAttempts int32     `json:"max_attempts"`
	RunAt       time.Time `json:"run_at"`
	Payload     []byte    `json:"payload"`
	CreatedBy   *int64    `json:"created_by"`
	ServerID    *int64    `json:"server_id"`
	DedupeKey   *string   `json:"dedupe_key"`
}

// Jobs ----------------------------------------------------------------------
//
// ClaimJob is the critical path. It is an UPDATE ... RETURNING, so the claim
// COMMITS before the row is scanned. If the scan fails, the caller sees an
// error while the job is already marked running -- a naive retry would strand
// it forever. Two consequences, both deliberate:
//
//  1. the generated row types must scan cleanly on both dialects (hence the
//     JSON []byte and timestamp overrides in sqlc.yaml);
//  2. a test asserts that a returned error means the job was NOT claimed.
//
// On PostgreSQL, FOR UPDATE SKIP LOCKED lets several workers claim jobs
// concurrently without blocking each other or double-claiming.
// SQLite has no equivalent, so its variant runs under a single-writer pool and
// the limitation is documented rather than papered over (Design Spec §22.3).
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.Kind,
		arg.Priority,
		arg.MaxAttempts,
		arg.RunAt,
		arg.Payload,
		arg.CreatedBy,
		arg.ServerID,
		arg.DedupeKey,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.Payload,
		&i.Progress,
		&i.LastError,
		&i.CreatedBy,
		&i.ServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DedupeKey,
	)
	return i, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs
SET status     = 'retrying',
    run_at     = $2,
    last_error = $3,
    updated_at = now(),
    locked_by  = NULL,
    locked_at  = NULL
WHERE id = $1
`

type FailJobParams struct {
	ID        int64     `json:"id"`
	RunAt     time.Time `json:"run_at"`
	LastError string    `json:"last_error"`
}

// Transient failure with attempts remaining: schedule a retry.
func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.ID, arg.RunAt, arg.LastError)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, kind, status, priority, attempts, max_attempts, run_at, locked_by, locked_at, payload, progress, last_error, created_by, server_id, created_at, updated_at, finished_at, dedupe_key FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.Payload,
		&i.Progress,
		&i.LastError,
		&i.CreatedBy,
		&i.ServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.DedupeKey,
	)
	return i, err
}

const heartbeatJob = `-- name: HeartbeatJob :exec
UPDATE jobs SET locked_at = now() WHERE id = $1 AND status = 'running'
`

// Refreshes the lease so the reaper does not reclaim a job that is still
// running.
func (q *Queries) HeartbeatJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, heartbeatJob, id)
	return err
}

const listJobs = `-- name: ListJobs :many
SELECT id, kind, status, priority, attempts, max_attempts, run_at, locked_by, locked_at, payload, progress, last_error, created_by, server_id, created_at, updated_at, finished_at, dedupe_key FROM jobs
WHERE ($3::text IS NULL OR status = $3::text)
  AND ($4::text IS NULL OR kind = $4::text)
  AND ($5::bigint IS NULL OR server_id = $5::bigint)
  AND ($6::bigint IS NULL OR created_by = $6::bigint)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit     int32   `json:"limit"`
	Offset    int32   `json:"offset"`
	Status    *string `json:"status"`
	Kind      *string `json:"kind"`
	ServerID  *int64  `json:"server_id"`
	CreatedBy *int64  `json:"created_by"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Kind,
		arg.ServerID,
		arg.CreatedBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.Priority,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RunAt,
			&i.LockedBy,
			&i.LockedAt,
			&i.Payload,
			&i.Progress,
			&i.LastError,
			&i.CreatedBy,
			&i.ServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.DedupeKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleJobs = `-- name: ListStaleJobs :many
SELECT id, kind, status, priority, attempts, max_attempts, run_at, locked_by, locked_at, payload, progress, last_error, created_by, server_id, created_at, updated_at, finished_at, dedupe_key FROM jobs
WHERE status = 'running' AND locked_at IS NOT NULL AND locked_at < $1
ORDER BY id
`

// Jobs whose worker stopped heartbeating. A crash leaves these behind; without
// reaping they would sit in 'running' forever.
func (q *Queries) ListStaleJobs(ctx context.Context, lockedAt *time.Time) ([]Job, error) {
	rows, err := q.db.Query(ctx, listStaleJobs, lockedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.Priority,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RunAt,
			&i.LockedBy,
			&i.LockedAt,
			&i.Payload,
			&i.Progress,
			&i.LastError,
			&i.CreatedBy,
			&i.ServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.DedupeKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteRetryingJobs = `-- name: PromoteRetryingJobs :execrows
UPDATE jobs SET status = 'queued', updated_at = now()
WHERE status = 'retrying' AND run_at <= now()
`

// Moves due retries back to queued so the claim query can pick them up.
func (q *Queries) PromoteRetryingJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, promoteRetryingJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueJob = `-- name: RequeueJob :exec
UPDATE jobs
SET status = 'queued', run_at = $2, locked_by = NULL, locked_at = NULL, updated_at = now()
WHERE id = $1
`

type RequeueJobParams struct {
	ID    int64     `json:"id"`
	RunAt time.Time `json:"run_at"`
}

// Returns a job to the queue without counting an attempt, used by the reaper
// when a worker disappears.
func (q *Queries) RequeueJob(ctx context.Context, arg RequeueJobParams) error {
	_, err := q.db.Exec(ctx, requeueJob, arg.ID, arg.RunAt)
	return err
}

const updateJobProgress = `-- name: UpdateJobProgress :exec
UPDATE jobs SET progress = $2, updated_at = now() WHERE id = $1
`

type UpdateJobProgressParams struct {
	ID       int64   `json:"id"`
	Progress float64 `json:"progress"`
}

func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) error {
	_, err := q.db.Exec(ctx, updateJobProgress, arg.ID, arg.Progress)
	return err
}
