// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: misc.sql

package storepg

import (
	"context"
	"time"
)

const closeTerminalSession = `-- name: CloseTerminalSession :exec
UPDATE terminal_sessions SET closed_at = now(), close_reason = $2
WHERE id = $1 AND closed_at IS NULL
`

type CloseTerminalSessionParams struct {
	ID          string `json:"id"`
	CloseReason string `json:"close_reason"`
}

func (q *Queries) CloseTerminalSession(ctx context.Context, arg CloseTerminalSessionParams) error {
	_, err := q.db.Exec(ctx, closeTerminalSession, arg.ID, arg.CloseReason)
	return err
}

const closeTerminalSessionsForServer = `-- name: CloseTerminalSessionsForServer :execrows
UPDATE terminal_sessions SET closed_at = now(), close_reason = $2
WHERE server_id = $1 AND closed_at IS NULL
`

type CloseTerminalSessionsForServerParams struct {
	ServerID    int64  `json:"server_id"`
	CloseReason string `json:"close_reason"`
}

func (q *Queries) CloseTerminalSessionsForServer(ctx context.Context, arg CloseTerminalSessionsForServerParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeTerminalSessionsForServer, arg.ServerID, arg.CloseReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeTerminalSessionsForUser = `-- name: CloseTerminalSessionsForUser :execrows
UPDATE terminal_sessions SET closed_at = now(), close_reason = $2
WHERE user_id = $1 AND closed_at IS NULL
`

type CloseTerminalSessionsForUserParams struct {
	UserID      int64  `json:"user_id"`
	CloseReason string `json:"close_reason"`
}

func (q *Queries) CloseTerminalSessionsForUser(ctx context.Context, arg CloseTerminalSessionsForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeTerminalSessionsForUser, arg.UserID, arg.CloseReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOpenTerminalSessions = `-- name: CountOpenTerminalSessions :one
SELECT count(*) FROM terminal_sessions WHERE closed_at IS NULL
`

func (q *Queries) CountOpenTerminalSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenTerminalSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenTerminalSessionsForServer = `-- name: CountOpenTerminalSessionsForServer :one
SELECT count(*) FROM terminal_sessions WHERE server_id = $1 AND closed_at IS NULL
`

func (q *Queries) CountOpenTerminalSessionsForServer(ctx context.Context, serverID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenTerminalSessionsForServer, serverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenTerminalSessionsForUser = `-- name: CountOpenTerminalSessionsForUser :one
SELECT count(*) FROM terminal_sessions WHERE user_id = $1 AND closed_at IS NULL
`

func (q *Queries) CountOpenTerminalSessionsForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenTerminalSessionsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE is_read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one

INSERT INTO api_tokens (user_id, name, token_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, token_hash, scopes, created_at, expires_at, last_used_at, revoked_at
`

type CreateAPITokenParams struct {
	UserID    int64      `json:"user_id"`
	Name      string     `json:"name"`
	TokenHash []byte     `json:"token_hash"`
	Scopes    []byte     `json:"scopes"`
	ExpiresAt *time.Time `json:"expires_at"`
}

// API tokens -----------------------------------------------------------------
//
// Only the SHA-256 hash is stored. The raw token is returned once, at creation,
// and is unrecoverable afterwards.
func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createBackup = `-- name: CreateBackup :one

INSERT INTO backups (filename, path, status, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, filename, path, size_bytes, checksum, status, error, started_at, finished_at, created_by
`

type CreateBackupParams struct {
	Filename  string `json:"filename"`
	Path      string `json:"path"`
	Status    string `json:"status"`
	CreatedBy *int64 `json:"created_by"`
}

// Backups ---------------------------------------------------------------------
func (q *Queries) CreateBackup(ctx context.Context, arg CreateBackupParams) (Backup, error) {
	row := q.db.QueryRow(ctx, createBackup,
		arg.Filename,
		arg.Path,
		arg.Status,
		arg.CreatedBy,
	)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Path,
		&i.SizeBytes,
		&i.Checksum,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (kind, severity, title, body, server_id, dedupe_key)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (dedupe_key) DO UPDATE SET
    title      = EXCLUDED.title,
    body       = EXCLUDED.body,
    severity   = EXCLUDED.severity,
    ts         = now(),
    is_read    = FALSE
RETURNING id, ts, kind, severity, title, body, server_id, dedupe_key, is_read, created_at
`

type CreateNotificationParams struct {
	Kind      string `json:"kind"`
	Severity  string `json:"severity"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	ServerID  *int64 `json:"server_id"`
	DedupeKey string `json:"dedupe_key"`
}

// Notifications ---------------------------------------------------------------
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.Kind,
		arg.Severity,
		arg.Title,
		arg.Body,
		arg.ServerID,
		arg.DedupeKey,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.Kind,
		&i.Severity,
		&i.Title,
		&i.Body,
		&i.ServerID,
		&i.DedupeKey,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const createTerminalSession = `-- name: CreateTerminalSession :one

INSERT INTO terminal_sessions (id, user_id, server_id, session_id, cols, rows)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, server_id, session_id, cols, rows, opened_at, closed_at, close_reason
`

type CreateTerminalSessionParams struct {
	ID        string `json:"id"`
	UserID    int64  `json:"user_id"`
	ServerID  int64  `json:"server_id"`
	SessionID string `json:"session_id"`
	Cols      int32  `json:"cols"`
	Rows      int32  `json:"rows"`
}

// Terminal sessions -----------------------------------------------------------
//
// Metadata only. Terminal input and output are never persisted: recording
// keystrokes would capture every secret an operator types (Design Spec §27.5).
func (q *Queries) CreateTerminalSession(ctx context.Context, arg CreateTerminalSessionParams) (TerminalSession, error) {
	row := q.db.QueryRow(ctx, createTerminalSession,
		arg.ID,
		arg.UserID,
		arg.ServerID,
		arg.SessionID,
		arg.Cols,
		arg.Rows,
	)
	var i TerminalSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.SessionID,
		&i.Cols,
		&i.Rows,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CloseReason,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = $1
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, id)
	return err
}

const deleteBackup = `-- name: DeleteBackup :exec
DELETE FROM backups WHERE id = $1
`

func (q *Queries) DeleteBackup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBackup, id)
	return err
}

const deleteClosedTerminalSessionsBefore = `-- name: DeleteClosedTerminalSessionsBefore :execrows
DELETE FROM terminal_sessions WHERE closed_at IS NOT NULL AND closed_at < $1
`

func (q *Queries) DeleteClosedTerminalSessionsBefore(ctx context.Context, closedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClosedTerminalSessionsBefore, closedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAPITokens = `-- name: DeleteExpiredAPITokens :execrows
DELETE FROM api_tokens WHERE expires_at IS NOT NULL AND expires_at < $1
`

func (q *Queries) DeleteExpiredAPITokens(ctx context.Context, expiresAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAPITokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotificationsBefore = `-- name: DeleteNotificationsBefore :execrows
DELETE FROM notifications WHERE ts < $1
`

func (q *Queries) DeleteNotificationsBefore(ctx context.Context, ts time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationsBefore, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSetting, key)
	return err
}

const finishBackup = `-- name: FinishBackup :exec
UPDATE backups
SET status = $2, size_bytes = $3, checksum = $4, error = $5, finished_at = now()
WHERE id = $1
`

type FinishBackupParams struct {
	ID        int64  `json:"id"`
	Status    string `json:"status"`
	SizeBytes int64  `json:"size_bytes"`
	Checksum  string `json:"checksum"`
	Error     string `json:"error"`
}

func (q *Queries) FinishBackup(ctx context.Context, arg FinishBackupParams) error {
	_, err := q.db.Exec(ctx, finishBackup,
		arg.ID,
		arg.Status,
		arg.SizeBytes,
		arg.Checksum,
		arg.Error,
	)
	return err
}

const getAPIToken = `-- name: GetAPIToken :one
SELECT id, user_id, name, token_hash, scopes, created_at, expires_at, last_used_at, revoked_at FROM api_tokens WHERE id = $1
`

func (q *Queries) GetAPIToken(ctx context.Context, id int64) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPIToken, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, token_hash, scopes, created_at, expires_at, last_used_at, revoked_at FROM api_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash []byte) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getBackup = `-- name: GetBackup :one
SELECT id, filename, path, size_bytes, checksum, status, error, started_at, finished_at, created_by FROM backups WHERE id = $1
`

func (q *Queries) GetBackup(ctx context.Context, id int64) (Backup, error) {
	row := q.db.QueryRow(ctx, getBackup, id)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Path,
		&i.SizeBytes,
		&i.Checksum,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT key, value, updated_at, updated_by FROM settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getTerminalSession = `-- name: GetTerminalSession :one
SELECT id, user_id, server_id, session_id, cols, rows, opened_at, closed_at, close_reason FROM terminal_sessions WHERE id = $1
`

func (q *Queries) GetTerminalSession(ctx context.Context, id string) (TerminalSession, error) {
	row := q.db.QueryRow(ctx, getTerminalSession, id)
	var i TerminalSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.SessionID,
		&i.Cols,
		&i.Rows,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CloseReason,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, user_id, name, token_hash, scopes, created_at, expires_at, last_used_at, revoked_at FROM api_tokens WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPITokens(ctx context.Context, userID int64) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Scopes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAPITokens = `-- name: ListAllAPITokens :many
SELECT t.id, t.user_id, t.name, t.token_hash, t.scopes, t.created_at, t.expires_at, t.last_used_at, t.revoked_at, u.username FROM api_tokens t
JOIN users u ON u.id = t.user_id
ORDER BY t.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllAPITokensParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllAPITokensRow struct {
	ID         int64      `json:"id"`
	UserID     int64      `json:"user_id"`
	Name       string     `json:"name"`
	TokenHash  []byte     `json:"token_hash"`
	Scopes     []byte     `json:"scopes"`
	CreatedAt  time.Time  `json:"created_at"`
	ExpiresAt  *time.Time `json:"expires_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	Username   string     `json:"username"`
}

func (q *Queries) ListAllAPITokens(ctx context.Context, arg ListAllAPITokensParams) ([]ListAllAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listAllAPITokens, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllAPITokensRow{}
	for rows.Next() {
		var i ListAllAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Scopes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackups = `-- name: ListBackups :many
SELECT id, filename, path, size_bytes, checksum, status, error, started_at, finished_at, created_by FROM backups ORDER BY started_at DESC LIMIT $1 OFFSET $2
`

type ListBackupsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBackups(ctx context.Context, arg ListBackupsParams) ([]Backup, error) {
	rows, err := q.db.Query(ctx, listBackups, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backup{}
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Path,
			&i.SizeBytes,
			&i.Checksum,
			&i.Status,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupsToPrune = `-- name: ListBackupsToPrune :many
SELECT id, filename, path, size_bytes, checksum, status, error, started_at, finished_at, created_by FROM backups
WHERE status = 'succeeded'
ORDER BY started_at DESC
OFFSET $1
`

func (q *Queries) ListBackupsToPrune(ctx context.Context, offset int32) ([]Backup, error) {
	rows, err := q.db.Query(ctx, listBackupsToPrune, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backup{}
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Path,
			&i.SizeBytes,
			&i.Checksum,
			&i.Status,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, ts, kind, severity, title, body, server_id, dedupe_key, is_read, created_at FROM notifications
WHERE ($3::boolean IS NULL OR is_read = FALSE)
ORDER BY ts DESC
LIMIT $1 OFFSET $2
`

type ListNotificationsParams struct {
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
	UnreadOnly *bool `json:"unread_only"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.Limit, arg.Offset, arg.UnreadOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Kind,
			&i.Severity,
			&i.Title,
			&i.Body,
			&i.ServerID,
			&i.DedupeKey,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenTerminalSessions = `-- name: ListOpenTerminalSessions :many
SELECT id, user_id, server_id, session_id, cols, rows, opened_at, closed_at, close_reason FROM terminal_sessions WHERE closed_at IS NULL ORDER BY opened_at
`

func (q *Queries) ListOpenTerminalSessions(ctx context.Context) ([]TerminalSession, error) {
	rows, err := q.db.Query(ctx, listOpenTerminalSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TerminalSession{}
	for rows.Next() {
		var i TerminalSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.SessionID,
			&i.Cols,
			&i.Rows,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CloseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, updated_at, updated_by FROM settings ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTerminalSessions = `-- name: ListUserTerminalSessions :many
SELECT id, user_id, server_id, session_id, cols, rows, opened_at, closed_at, close_reason FROM terminal_sessions WHERE user_id = $1 ORDER BY opened_at DESC LIMIT $2
`

type ListUserTerminalSessionsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListUserTerminalSessions(ctx context.Context, arg ListUserTerminalSessionsParams) ([]TerminalSession, error) {
	rows, err := q.db.Query(ctx, listUserTerminalSessions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TerminalSession{}
	for rows.Next() {
		var i TerminalSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.SessionID,
			&i.Cols,
			&i.Rows,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CloseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = TRUE WHERE is_read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = TRUE WHERE id = $1
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotificationRead, id)
	return err
}

const ping = `-- name: Ping :one

SELECT 1 AS ok
`

// Health ----------------------------------------------------------------------
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeAPIToken, id)
	return err
}

const revokeUserAPITokens = `-- name: RevokeUserAPITokens :execrows
UPDATE api_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserAPITokens(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserAPITokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec

INSERT INTO settings (key, value, updated_by, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (key) DO UPDATE SET
    value      = EXCLUDED.value,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
`

type UpsertSettingParams struct {
	Key       string `json:"key"`
	Value     []byte `json:"value"`
	UpdatedBy *int64 `json:"updated_by"`
}

// Settings -------------------------------------------------------------------
func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value, arg.UpdatedBy)
	return err
}
