// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: servers.sql

package storepg

import (
	"context"
	"time"
)

const addServerTag = `-- name: AddServerTag :exec
INSERT INTO server_tags (server_id, tag_id) VALUES ($1, $2)
ON CONFLICT (server_id, tag_id) DO NOTHING
`

type AddServerTagParams struct {
	ServerID int64 `json:"server_id"`
	TagID    int64 `json:"tag_id"`
}

func (q *Queries) AddServerTag(ctx context.Context, arg AddServerTagParams) error {
	_, err := q.db.Exec(ctx, addServerTag, arg.ServerID, arg.TagID)
	return err
}

const clearServerPermissions = `-- name: ClearServerPermissions :exec
DELETE FROM server_permissions WHERE user_id = $1 AND server_id = $2
`

type ClearServerPermissionsParams struct {
	UserID   int64 `json:"user_id"`
	ServerID int64 `json:"server_id"`
}

func (q *Queries) ClearServerPermissions(ctx context.Context, arg ClearServerPermissionsParams) error {
	_, err := q.db.Exec(ctx, clearServerPermissions, arg.UserID, arg.ServerID)
	return err
}

const clearServerTags = `-- name: ClearServerTags :exec
DELETE FROM server_tags WHERE server_id = $1
`

func (q *Queries) ClearServerTags(ctx context.Context, serverID int64) error {
	_, err := q.db.Exec(ctx, clearServerTags, serverID)
	return err
}

const countServerPermissionsForUser = `-- name: CountServerPermissionsForUser :one
SELECT count(*) FROM server_permissions WHERE user_id = $1 AND server_id = $2
`

type CountServerPermissionsForUserParams struct {
	UserID   int64 `json:"user_id"`
	ServerID int64 `json:"server_id"`
}

func (q *Queries) CountServerPermissionsForUser(ctx context.Context, arg CountServerPermissionsForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countServerPermissionsForUser, arg.UserID, arg.ServerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServers = `-- name: CountServers :one
SELECT count(*) FROM servers
WHERE ($1::text IS NULL
       OR name ILIKE '%' || $1::text || '%'
       OR host ILIKE '%' || $1::text || '%'
       OR username ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR target_type = $3::text)
  -- Tag filtering uses a substring match on the JSON array text with the
  -- surrounding quotes included, which is precise enough for tag names and
  -- portable across both dialects. PostgreSQL's jsonb @> operator would be
  -- exact but has no SQLite equivalent.
  AND ($4::text IS NULL
       OR tags LIKE '%"' || $4::text || '"%')
`

type CountServersParams struct {
	Search     *string `json:"search"`
	Status     *string `json:"status"`
	TargetType *string `json:"target_type"`
	Tag        *string `json:"tag"`
}

func (q *Queries) CountServers(ctx context.Context, arg CountServersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countServers,
		arg.Search,
		arg.Status,
		arg.TargetType,
		arg.Tag,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServersByStatus = `-- name: CountServersByStatus :many
SELECT status, count(*) AS count FROM servers GROUP BY status
`

type CountServersByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountServersByStatus(ctx context.Context) ([]CountServersByStatusRow, error) {
	rows, err := q.db.Query(ctx, countServersByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountServersByStatusRow{}
	for rows.Next() {
		var i CountServersByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createServer = `-- name: CreateServer :one

INSERT INTO servers (name, target_type, host, port, username, auth_method,
                     host_key_policy, tags, notes, is_favourite)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, target_type, host, port, username, auth_method, host_key_policy, tags, notes, is_favourite, status, status_detail, os, kernel, arch, last_seen_at, last_error_at, created_at, updated_at, version
`

type CreateServerParams struct {
	Name          string `json:"name"`
	TargetType    string `json:"target_type"`
	Host          string `json:"host"`
	Port          int32  `json:"port"`
	Username      string `json:"username"`
	AuthMethod    string `json:"auth_method"`
	HostKeyPolicy string `json:"host_key_policy"`
	Tags          []byte `json:"tags"`
	Notes         string `json:"notes"`
	IsFavourite   bool   `json:"is_favourite"`
}

// Servers -------------------------------------------------------------------
func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.Name,
		arg.TargetType,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.AuthMethod,
		arg.HostKeyPolicy,
		arg.Tags,
		arg.Notes,
		arg.IsFavourite,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetType,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.AuthMethod,
		&i.HostKeyPolicy,
		&i.Tags,
		&i.Notes,
		&i.IsFavourite,
		&i.Status,
		&i.StatusDetail,
		&i.Os,
		&i.Kernel,
		&i.Arch,
		&i.LastSeenAt,
		&i.LastErrorAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createServerCredential = `-- name: CreateServerCredential :one

INSERT INTO server_credentials (server_id, kind, ciphertext, version)
VALUES ($1, $2, $3, $4)
RETURNING id, server_id, kind, ciphertext, version, created_at, rotated_at
`

type CreateServerCredentialParams struct {
	ServerID   int64  `json:"server_id"`
	Kind       string `json:"kind"`
	Ciphertext []byte `json:"ciphertext"`
	Version    int64  `json:"version"`
}

// Credentials ----------------------------------------------------------------
func (q *Queries) CreateServerCredential(ctx context.Context, arg CreateServerCredentialParams) (ServerCredential, error) {
	row := q.db.QueryRow(ctx, createServerCredential,
		arg.ServerID,
		arg.Kind,
		arg.Ciphertext,
		arg.Version,
	)
	var i ServerCredential
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Kind,
		&i.Ciphertext,
		&i.Version,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const createServerHostKey = `-- name: CreateServerHostKey :one
INSERT INTO server_host_keys (server_id, algorithm, fingerprint, public_key, state, trusted_at, trusted_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, server_id, algorithm, fingerprint, public_key, state, first_seen, trusted_at, trusted_by
`

type CreateServerHostKeyParams struct {
	ServerID    int64      `json:"server_id"`
	Algorithm   string     `json:"algorithm"`
	Fingerprint string     `json:"fingerprint"`
	PublicKey   []byte     `json:"public_key"`
	State       string     `json:"state"`
	TrustedAt   *time.Time `json:"trusted_at"`
	TrustedBy   *int64     `json:"trusted_by"`
}

func (q *Queries) CreateServerHostKey(ctx context.Context, arg CreateServerHostKeyParams) (ServerHostKey, error) {
	row := q.db.QueryRow(ctx, createServerHostKey,
		arg.ServerID,
		arg.Algorithm,
		arg.Fingerprint,
		arg.PublicKey,
		arg.State,
		arg.TrustedAt,
		arg.TrustedBy,
	)
	var i ServerHostKey
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Algorithm,
		&i.Fingerprint,
		&i.PublicKey,
		&i.State,
		&i.FirstSeen,
		&i.TrustedAt,
		&i.TrustedBy,
	)
	return i, err
}

const deleteOrphanTags = `-- name: DeleteOrphanTags :execrows
DELETE FROM tags WHERE id NOT IN (SELECT DISTINCT tag_id FROM server_tags)
`

func (q *Queries) DeleteOrphanTags(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanTags)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers WHERE id = $1
`

// Deleting a server removes only the panel's configuration. It never touches
// the remote host. Credentials and host keys cascade.
func (q *Queries) DeleteServer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteServer, id)
	return err
}

const deleteServerCredentials = `-- name: DeleteServerCredentials :exec
DELETE FROM server_credentials WHERE server_id = $1
`

func (q *Queries) DeleteServerCredentials(ctx context.Context, serverID int64) error {
	_, err := q.db.Exec(ctx, deleteServerCredentials, serverID)
	return err
}

const deleteServerHostKeys = `-- name: DeleteServerHostKeys :exec
DELETE FROM server_host_keys WHERE server_id = $1
`

// Replacing a changed host key is an explicit, audited action; it never
// happens as a side effect of connecting.
func (q *Queries) DeleteServerHostKeys(ctx context.Context, serverID int64) error {
	_, err := q.db.Exec(ctx, deleteServerHostKeys, serverID)
	return err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, name, target_type, host, port, username, auth_method, host_key_policy, tags, notes, is_favourite, status, status_detail, os, kernel, arch, last_seen_at, last_error_at, created_at, updated_at, version FROM servers WHERE id = $1
`

func (q *Queries) GetServerByID(ctx context.Context, id int64) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetType,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.AuthMethod,
		&i.HostKeyPolicy,
		&i.Tags,
		&i.Notes,
		&i.IsFavourite,
		&i.Status,
		&i.StatusDetail,
		&i.Os,
		&i.Kernel,
		&i.Arch,
		&i.LastSeenAt,
		&i.LastErrorAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getServerByName = `-- name: GetServerByName :one
SELECT id, name, target_type, host, port, username, auth_method, host_key_policy, tags, notes, is_favourite, status, status_detail, os, kernel, arch, last_seen_at, last_error_at, created_at, updated_at, version FROM servers WHERE name = $1
`

func (q *Queries) GetServerByName(ctx context.Context, name string) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByName, name)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetType,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.AuthMethod,
		&i.HostKeyPolicy,
		&i.Tags,
		&i.Notes,
		&i.IsFavourite,
		&i.Status,
		&i.StatusDetail,
		&i.Os,
		&i.Kernel,
		&i.Arch,
		&i.LastSeenAt,
		&i.LastErrorAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getServerCredential = `-- name: GetServerCredential :one
SELECT id, server_id, kind, ciphertext, version, created_at, rotated_at FROM server_credentials
WHERE server_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetServerCredential(ctx context.Context, serverID int64) (ServerCredential, error) {
	row := q.db.QueryRow(ctx, getServerCredential, serverID)
	var i ServerCredential
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Kind,
		&i.Ciphertext,
		&i.Version,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const getServerHostKey = `-- name: GetServerHostKey :one

SELECT id, server_id, algorithm, fingerprint, public_key, state, first_seen, trusted_at, trusted_by FROM server_host_keys WHERE server_id = $1 ORDER BY first_seen DESC LIMIT 1
`

// Host keys ------------------------------------------------------------------
func (q *Queries) GetServerHostKey(ctx context.Context, serverID int64) (ServerHostKey, error) {
	row := q.db.QueryRow(ctx, getServerHostKey, serverID)
	var i ServerHostKey
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Algorithm,
		&i.Fingerprint,
		&i.PublicKey,
		&i.State,
		&i.FirstSeen,
		&i.TrustedAt,
		&i.TrustedBy,
	)
	return i, err
}

const getServerHostKeyByFingerprint = `-- name: GetServerHostKeyByFingerprint :one
SELECT id, server_id, algorithm, fingerprint, public_key, state, first_seen, trusted_at, trusted_by FROM server_host_keys WHERE server_id = $1 AND fingerprint = $2
`

type GetServerHostKeyByFingerprintParams struct {
	ServerID    int64  `json:"server_id"`
	Fingerprint string `json:"fingerprint"`
}

func (q *Queries) GetServerHostKeyByFingerprint(ctx context.Context, arg GetServerHostKeyByFingerprintParams) (ServerHostKey, error) {
	row := q.db.QueryRow(ctx, getServerHostKeyByFingerprint, arg.ServerID, arg.Fingerprint)
	var i ServerHostKey
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Algorithm,
		&i.Fingerprint,
		&i.PublicKey,
		&i.State,
		&i.FirstSeen,
		&i.TrustedAt,
		&i.TrustedBy,
	)
	return i, err
}

const grantServerPermission = `-- name: GrantServerPermission :exec
INSERT INTO server_permissions (user_id, server_id, permission_id, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, server_id, permission_id) DO NOTHING
`

type GrantServerPermissionParams struct {
	UserID       int64  `json:"user_id"`
	ServerID     int64  `json:"server_id"`
	PermissionID int64  `json:"permission_id"`
	GrantedBy    *int64 `json:"granted_by"`
}

func (q *Queries) GrantServerPermission(ctx context.Context, arg GrantServerPermissionParams) error {
	_, err := q.db.Exec(ctx, grantServerPermission,
		arg.UserID,
		arg.ServerID,
		arg.PermissionID,
		arg.GrantedBy,
	)
	return err
}

const listAccessibleServerIDs = `-- name: ListAccessibleServerIDs :many
SELECT DISTINCT sp.server_id FROM server_permissions sp WHERE sp.user_id = $1
`

// Servers a user may see. An administrator sees everything; anyone else sees
// only servers with at least one explicit grant. Returning 404 (not 403) for
// the others avoids disclosing that they exist.
func (q *Queries) ListAccessibleServerIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAccessibleServerIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var server_id int64
		if err := rows.Scan(&server_id); err != nil {
			return nil, err
		}
		items = append(items, server_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllServers = `-- name: ListAllServers :many
SELECT id, name, target_type, host, port, username, auth_method, host_key_policy, tags, notes, is_favourite, status, status_detail, os, kernel, arch, last_seen_at, last_error_at, created_at, updated_at, version FROM servers ORDER BY id
`

// Used by background workers that operate across every server.
func (q *Queries) ListAllServers(ctx context.Context) ([]Server, error) {
	rows, err := q.db.Query(ctx, listAllServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetType,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.AuthMethod,
			&i.HostKeyPolicy,
			&i.Tags,
			&i.Notes,
			&i.IsFavourite,
			&i.Status,
			&i.StatusDetail,
			&i.Os,
			&i.Kernel,
			&i.Arch,
			&i.LastSeenAt,
			&i.LastErrorAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialCiphertexts = `-- name: ListCredentialCiphertexts :many
SELECT id, server_id, ciphertext FROM server_credentials ORDER BY id
`

type ListCredentialCiphertextsRow struct {
	ID         int64  `json:"id"`
	ServerID   int64  `json:"server_id"`
	Ciphertext []byte `json:"ciphertext"`
}

// Used by the key-rotation sweep.
func (q *Queries) ListCredentialCiphertexts(ctx context.Context) ([]ListCredentialCiphertextsRow, error) {
	rows, err := q.db.Query(ctx, listCredentialCiphertexts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialCiphertextsRow{}
	for rows.Next() {
		var i ListCredentialCiphertextsRow
		if err := rows.Scan(&i.ID, &i.ServerID, &i.Ciphertext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServerHostKeys = `-- name: ListServerHostKeys :many
SELECT id, server_id, algorithm, fingerprint, public_key, state, first_seen, trusted_at, trusted_by FROM server_host_keys WHERE server_id = $1 ORDER BY first_seen DESC
`

func (q *Queries) ListServerHostKeys(ctx context.Context, serverID int64) ([]ServerHostKey, error) {
	rows, err := q.db.Query(ctx, listServerHostKeys, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServerHostKey{}
	for rows.Next() {
		var i ServerHostKey
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Algorithm,
			&i.Fingerprint,
			&i.PublicKey,
			&i.State,
			&i.FirstSeen,
			&i.TrustedAt,
			&i.TrustedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServerIDs = `-- name: ListServerIDs :many
SELECT id FROM servers ORDER BY id
`

func (q *Queries) ListServerIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listServerIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServerPermissionGrants = `-- name: ListServerPermissionGrants :many
SELECT sp.server_id, p.name FROM server_permissions sp
JOIN permissions p ON p.id = sp.permission_id
WHERE sp.user_id = $1
`

type ListServerPermissionGrantsRow struct {
	ServerID int64  `json:"server_id"`
	Name     string `json:"name"`
}

func (q *Queries) ListServerPermissionGrants(ctx context.Context, userID int64) ([]ListServerPermissionGrantsRow, error) {
	rows, err := q.db.Query(ctx, listServerPermissionGrants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServerPermissionGrantsRow{}
	for rows.Next() {
		var i ListServerPermissionGrantsRow
		if err := rows.Scan(&i.ServerID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServerPermissions = `-- name: ListServerPermissions :many

SELECT p.name FROM server_permissions sp
JOIN permissions p ON p.id = sp.permission_id
WHERE sp.user_id = $1 AND sp.server_id = $2
ORDER BY p.name
`

type ListServerPermissionsParams struct {
	UserID   int64 `json:"user_id"`
	ServerID int64 `json:"server_id"`
}

// Per-server permissions ------------------------------------------------------
func (q *Queries) ListServerPermissions(ctx context.Context, arg ListServerPermissionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listServerPermissions, arg.UserID, arg.ServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServers = `-- name: ListServers :many
SELECT id, name, target_type, host, port, username, auth_method, host_key_policy, tags, notes, is_favourite, status, status_detail, os, kernel, arch, last_seen_at, last_error_at, created_at, updated_at, version FROM servers
WHERE ($3::text IS NULL
       OR name ILIKE '%' || $3::text || '%'
       OR host ILIKE '%' || $3::text || '%'
       OR username ILIKE '%' || $3::text || '%')
  AND ($4::text IS NULL OR status = $4::text)
  AND ($5::text IS NULL OR target_type = $5::text)
  -- Tag filtering uses a substring match on the JSON array text with the
  -- surrounding quotes included, which is precise enough for tag names and
  -- portable across both dialects. PostgreSQL's jsonb @> operator would be
  -- exact but has no SQLite equivalent.
  AND ($6::text IS NULL
       OR tags LIKE '%"' || $6::text || '"%')
ORDER BY is_favourite DESC, name
LIMIT $1 OFFSET $2
`

type ListServersParams struct {
	Limit      int32   `json:"limit"`
	Offset     int32   `json:"offset"`
	Search     *string `json:"search"`
	Status     *string `json:"status"`
	TargetType *string `json:"target_type"`
	Tag        *string `json:"tag"`
}

func (q *Queries) ListServers(ctx context.Context, arg ListServersParams) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServers,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Status,
		arg.TargetType,
		arg.Tag,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetType,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.AuthMethod,
			&i.HostKeyPolicy,
			&i.Tags,
			&i.Notes,
			&i.IsFavourite,
			&i.Status,
			&i.StatusDetail,
			&i.Os,
			&i.Kernel,
			&i.Arch,
			&i.LastSeenAt,
			&i.LastErrorAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, t.created_at, count(st.server_id) AS server_count FROM tags t
LEFT JOIN server_tags st ON st.tag_id = t.id
GROUP BY t.id, t.name, t.created_at
ORDER BY t.name
`

type ListTagsRow struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	CreatedAt   time.Time `json:"created_at"`
	ServerCount int64     `json:"server_count"`
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ServerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeServerTag = `-- name: RemoveServerTag :exec
DELETE FROM server_tags WHERE server_id = $1 AND tag_id = $2
`

type RemoveServerTagParams struct {
	ServerID int64 `json:"server_id"`
	TagID    int64 `json:"tag_id"`
}

func (q *Queries) RemoveServerTag(ctx context.Context, arg RemoveServerTagParams) error {
	_, err := q.db.Exec(ctx, removeServerTag, arg.ServerID, arg.TagID)
	return err
}

const revokeServerPermission = `-- name: RevokeServerPermission :exec
DELETE FROM server_permissions
WHERE user_id = $1 AND server_id = $2 AND permission_id = $3
`

type RevokeServerPermissionParams struct {
	UserID       int64 `json:"user_id"`
	ServerID     int64 `json:"server_id"`
	PermissionID int64 `json:"permission_id"`
}

func (q *Queries) RevokeServerPermission(ctx context.Context, arg RevokeServerPermissionParams) error {
	_, err := q.db.Exec(ctx, revokeServerPermission, arg.UserID, arg.ServerID, arg.PermissionID)
	return err
}

const rotateServerCredential = `-- name: RotateServerCredential :one
INSERT INTO server_credentials (server_id, kind, ciphertext, version)
SELECT $1, $2, $3, COALESCE(MAX(version), 0) + 1
FROM server_credentials WHERE server_id = $1
RETURNING id, server_id, kind, ciphertext, version, created_at, rotated_at
`

type RotateServerCredentialParams struct {
	ServerID   int64  `json:"server_id"`
	Kind       string `json:"kind"`
	Ciphertext []byte `json:"ciphertext"`
}

// Rotation bumps the version, which invalidates pooled connections keyed to
// the previous version.
func (q *Queries) RotateServerCredential(ctx context.Context, arg RotateServerCredentialParams) (ServerCredential, error) {
	row := q.db.QueryRow(ctx, rotateServerCredential, arg.ServerID, arg.Kind, arg.Ciphertext)
	var i ServerCredential
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Kind,
		&i.Ciphertext,
		&i.Version,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const serverNameExists = `-- name: ServerNameExists :one
SELECT EXISTS (SELECT 1 FROM servers WHERE name = $1 AND id <> $2) AS present
`

type ServerNameExistsParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) ServerNameExists(ctx context.Context, arg ServerNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, serverNameExists, arg.Name, arg.ID)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const updateCredentialCiphertext = `-- name: UpdateCredentialCiphertext :exec
UPDATE server_credentials SET ciphertext = $2, rotated_at = now() WHERE id = $1
`

type UpdateCredentialCiphertextParams struct {
	ID         int64  `json:"id"`
	Ciphertext []byte `json:"ciphertext"`
}

func (q *Queries) UpdateCredentialCiphertext(ctx context.Context, arg UpdateCredentialCiphertextParams) error {
	_, err := q.db.Exec(ctx, updateCredentialCiphertext, arg.ID, arg.Ciphertext)
	return err
}

const updateHostKeyState = `-- name: UpdateHostKeyState :exec
UPDATE server_host_keys SET state = $2, trusted_at = $3, trusted_by = $4 WHERE id = $1
`

type UpdateHostKeyStateParams struct {
	ID        int64      `json:"id"`
	State     string     `json:"state"`
	TrustedAt *time.Time `json:"trusted_at"`
	TrustedBy *int64     `json:"trusted_by"`
}

func (q *Queries) UpdateHostKeyState(ctx context.Context, arg UpdateHostKeyStateParams) error {
	_, err := q.db.Exec(ctx, updateHostKeyState,
		arg.ID,
		arg.State,
		arg.TrustedAt,
		arg.TrustedBy,
	)
	return err
}

const updateServer = `-- name: UpdateServer :one
UPDATE servers
SET name            = $2,
    host            = $3,
    port            = $4,
    username        = $5,
    auth_method     = $6,
    host_key_policy = $7,
    tags            = $8,
    notes           = $9,
    is_favourite    = $10,
    updated_at      = now(),
    version         = version + 1
WHERE id = $1 AND version = $11
RETURNING id, name, target_type, host, port, username, auth_method, host_key_policy, tags, notes, is_favourite, status, status_detail, os, kernel, arch, last_seen_at, last_error_at, created_at, updated_at, version
`

type UpdateServerParams struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Host          string `json:"host"`
	Port          int32  `json:"port"`
	Username      string `json:"username"`
	AuthMethod    string `json:"auth_method"`
	HostKeyPolicy string `json:"host_key_policy"`
	Tags          []byte `json:"tags"`
	Notes         string `json:"notes"`
	IsFavourite   bool   `json:"is_favourite"`
	Version       int64  `json:"version"`
}

// Versioned update: a stale version returns no rows, so two administrators
// editing the same server cannot silently overwrite each other.
func (q *Queries) UpdateServer(ctx context.Context, arg UpdateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServer,
		arg.ID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.AuthMethod,
		arg.HostKeyPolicy,
		arg.Tags,
		arg.Notes,
		arg.IsFavourite,
		arg.Version,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetType,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.AuthMethod,
		&i.HostKeyPolicy,
		&i.Tags,
		&i.Notes,
		&i.IsFavourite,
		&i.Status,
		&i.StatusDetail,
		&i.Os,
		&i.Kernel,
		&i.Arch,
		&i.LastSeenAt,
		&i.LastErrorAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateServerStatus = `-- name: UpdateServerStatus :one
UPDATE servers
SET status        = $2,
    status_detail = $3,
    last_seen_at  = CASE WHEN $2 = 'ONLINE' THEN now() ELSE last_seen_at END,
    last_error_at = CASE WHEN $2 IN ('OFFLINE','ERROR') THEN now() ELSE last_error_at END,
    updated_at    = now()
WHERE id = $1
RETURNING id, name, target_type, host, port, username, auth_method, host_key_policy, tags, notes, is_favourite, status, status_detail, os, kernel, arch, last_seen_at, last_error_at, created_at, updated_at, version
`

type UpdateServerStatusParams struct {
	ID           int64  `json:"id"`
	Status       string `json:"status"`
	StatusDetail string `json:"status_detail"`
}

func (q *Queries) UpdateServerStatus(ctx context.Context, arg UpdateServerStatusParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServerStatus, arg.ID, arg.Status, arg.StatusDetail)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetType,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.AuthMethod,
		&i.HostKeyPolicy,
		&i.Tags,
		&i.Notes,
		&i.IsFavourite,
		&i.Status,
		&i.StatusDetail,
		&i.Os,
		&i.Kernel,
		&i.Arch,
		&i.LastSeenAt,
		&i.LastErrorAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateServerSystemInfo = `-- name: UpdateServerSystemInfo :exec
UPDATE servers
SET os = $2, kernel = $3, arch = $4, updated_at = now()
WHERE id = $1
`

type UpdateServerSystemInfoParams struct {
	ID     int64  `json:"id"`
	Os     string `json:"os"`
	Kernel string `json:"kernel"`
	Arch   string `json:"arch"`
}

func (q *Queries) UpdateServerSystemInfo(ctx context.Context, arg UpdateServerSystemInfoParams) error {
	_, err := q.db.Exec(ctx, updateServerSystemInfo,
		arg.ID,
		arg.Os,
		arg.Kernel,
		arg.Arch,
	)
	return err
}

const upsertTag = `-- name: UpsertTag :one

INSERT INTO tags (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

// Tags -----------------------------------------------------------------------
func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
