// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package storepg

import (
	"context"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id) VALUES ($1, $2)
ON CONFLICT (role_id, permission_id) DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AddUserRoleParams struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.Exec(ctx, addUserRole, arg.UserID, arg.RoleID)
	return err
}

const clearRolePermissions = `-- name: ClearRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) ClearRolePermissions(ctx context.Context, roleID int64) error {
	_, err := q.db.Exec(ctx, clearRolePermissions, roleID)
	return err
}

const clearUserBootstrapFlag = `-- name: ClearUserBootstrapFlag :exec
UPDATE users SET is_bootstrap_default = FALSE, updated_at = now() WHERE id = $1
`

func (q *Queries) ClearUserBootstrapFlag(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearUserBootstrapFlag, id)
	return err
}

const clearUserRoles = `-- name: ClearUserRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) ClearUserRoles(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearUserRoles, userID)
	return err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(DISTINCT u.id) FROM users u
JOIN user_roles ur ON ur.user_id = u.id
JOIN roles r ON r.id = ur.role_id
WHERE u.deleted_at IS NULL AND u.is_active = TRUE AND r.name = 'admin'
`

// Guards against removing the last administrator.
func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllUsers = `-- name: CountAllUsers :one
SELECT count(*) FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE deleted_at IS NULL
  AND ($1::text IS NULL
       OR username ILIKE '%' || $1::text || '%'
       OR display_name ILIKE '%' || $1::text || '%')
  AND ($2::boolean IS NULL OR is_active = $2::boolean)
`

type CountUsersParams struct {
	Search   *string `json:"search"`
	IsActive *bool   `json:"is_active"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Search, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersWithDefaultCredentials = `-- name: CountUsersWithDefaultCredentials :one
SELECT count(*) FROM users WHERE is_bootstrap_default = TRUE AND deleted_at IS NULL
`

func (q *Queries) CountUsersWithDefaultCredentials(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithDefaultCredentials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPermission = `-- name: CreatePermission :one

INSERT INTO permissions (name, description) VALUES ($1, $2) RETURNING id, name, description
`

type CreatePermissionParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

// Permissions ----------------------------------------------------------------
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Name, arg.Description)
	var i Permission
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const createRole = `-- name: CreateRole :one

INSERT INTO roles (name, description, is_system) VALUES ($1, $2, $3) RETURNING id, name, description, is_system, created_at, updated_at
`

type CreateRoleParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	IsSystem    bool   `json:"is_system"`
}

// Roles ----------------------------------------------------------------------
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description, arg.IsSystem)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (username, password_hash, display_name, is_active,
                   is_bootstrap_default, must_change_password)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, password_hash, display_name, is_active, is_bootstrap_default, must_change_password, last_login_at, created_at, updated_at, deleted_at, version
`

type CreateUserParams struct {
	Username           string `json:"username"`
	PasswordHash       string `json:"password_hash"`
	DisplayName        string `json:"display_name"`
	IsActive           bool   `json:"is_active"`
	IsBootstrapDefault bool   `json:"is_bootstrap_default"`
	MustChangePassword bool   `json:"must_change_password"`
}

// Users ---------------------------------------------------------------------
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.IsActive,
		arg.IsBootstrapDefault,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsActive,
		&i.IsBootstrapDefault,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1 AND is_system = FALSE
`

func (q *Queries) DeleteRole(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getPermissionByName = `-- name: GetPermissionByName :one
SELECT id, name, description FROM permissions WHERE name = $1
`

func (q *Queries) GetPermissionByName(ctx context.Context, name string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByName, name)
	var i Permission
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, is_system, created_at, updated_at FROM roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id int64) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, is_system, created_at, updated_at FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, display_name, is_active, is_bootstrap_default, must_change_password, last_login_at, created_at, updated_at, deleted_at, version FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsActive,
		&i.IsBootstrapDefault,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, display_name, is_active, is_bootstrap_default, must_change_password, last_login_at, created_at, updated_at, deleted_at, version FROM users
WHERE lower(username) = lower($1) AND deleted_at IS NULL
`

// Usernames are compared case-insensitively, matching the partial unique index.
func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsActive,
		&i.IsBootstrapDefault,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const hasBootstrapDefaultUser = `-- name: HasBootstrapDefaultUser :one
SELECT EXISTS (
    SELECT 1 FROM users
    WHERE is_bootstrap_default = TRUE AND deleted_at IS NULL AND is_active = TRUE
) AS present
`

func (q *Queries) HasBootstrapDefaultUser(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasBootstrapDefaultUser)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, name, description FROM permissions ORDER BY name
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT p.id, p.name, p.description FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
ORDER BY p.name
`

func (q *Queries) ListRolePermissions(ctx context.Context, roleID int64) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, is_system, created_at, updated_at FROM roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissions = `-- name: ListUserPermissions :many
SELECT DISTINCT p.name FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE ur.user_id = $1
ORDER BY p.name
`

// Effective permissions from every role the user holds.
func (q *Queries) ListUserPermissions(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.name, r.description, r.is_system, r.created_at, r.updated_at FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.name
`

func (q *Queries) ListUserRoles(ctx context.Context, userID int64) ([]Role, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, display_name, is_active, is_bootstrap_default, must_change_password, last_login_at, created_at, updated_at, deleted_at, version FROM users
WHERE deleted_at IS NULL
  AND ($3::text IS NULL
       OR username ILIKE '%' || $3::text || '%'
       OR display_name ILIKE '%' || $3::text || '%')
  AND ($4::boolean IS NULL OR is_active = $4::boolean)
ORDER BY username
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
	Search   *string `json:"search"`
	IsActive *bool   `json:"is_active"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.IsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.DisplayName,
			&i.IsActive,
			&i.IsBootstrapDefault,
			&i.MustChangePassword,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordUserLogin = `-- name: RecordUserLogin :exec
UPDATE users SET last_login_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) RecordUserLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, recordUserLogin, id)
	return err
}

const removeRolePermission = `-- name: RemoveRolePermission :exec
DELETE FROM role_permissions WHERE role_id = $1 AND permission_id = $2
`

type RemoveRolePermissionParams struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

func (q *Queries) RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error {
	_, err := q.db.Exec(ctx, removeRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const removeUserRole = `-- name: RemoveUserRole :exec
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type RemoveUserRoleParams struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

func (q *Queries) RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error {
	_, err := q.db.Exec(ctx, removeUserRole, arg.UserID, arg.RoleID)
	return err
}

const setUserMustChangePassword = `-- name: SetUserMustChangePassword :exec
UPDATE users SET must_change_password = $2, updated_at = now() WHERE id = $1
`

type SetUserMustChangePasswordParams struct {
	ID                 int64 `json:"id"`
	MustChangePassword bool  `json:"must_change_password"`
}

func (q *Queries) SetUserMustChangePassword(ctx context.Context, arg SetUserMustChangePasswordParams) error {
	_, err := q.db.Exec(ctx, setUserMustChangePassword, arg.ID, arg.MustChangePassword)
	return err
}

const setUserPassword = `-- name: SetUserPassword :one
UPDATE users
SET password_hash        = $2,
    must_change_password = $3,
    -- Changing the password clears the bootstrap flag: the warning is driven
    -- by this flag, never by comparing against a stored default password.
    is_bootstrap_default = FALSE,
    updated_at           = now(),
    version              = version + 1
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, password_hash, display_name, is_active, is_bootstrap_default, must_change_password, last_login_at, created_at, updated_at, deleted_at, version
`

type SetUserPasswordParams struct {
	ID                 int64  `json:"id"`
	PasswordHash       string `json:"password_hash"`
	MustChangePassword bool   `json:"must_change_password"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPassword, arg.ID, arg.PasswordHash, arg.MustChangePassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsActive,
		&i.IsBootstrapDefault,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = now(), is_active = FALSE, updated_at = now(), version = version + 1
WHERE id = $1 AND deleted_at IS NULL
`

// Soft delete preserves audit history and avoids orphaning references.
func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET name = $2, description = $3, updated_at = now()
WHERE id = $1 AND is_system = FALSE
RETURNING id, name, description, is_system, created_at, updated_at
`

type UpdateRoleParams struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = $2,
    is_active    = $3,
    updated_at   = now(),
    version      = version + 1
WHERE id = $1 AND deleted_at IS NULL AND version = $4
RETURNING id, username, password_hash, display_name, is_active, is_bootstrap_default, must_change_password, last_login_at, created_at, updated_at, deleted_at, version
`

type UpdateUserParams struct {
	ID          int64  `json:"id"`
	DisplayName string `json:"display_name"`
	IsActive    bool   `json:"is_active"`
	Version     int64  `json:"version"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.IsActive,
		arg.Version,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsActive,
		&i.IsBootstrapDefault,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}
