// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package storesqlite

import (
	"context"
	"time"
)

const countApplicationLogs = `-- name: CountApplicationLogs :one
SELECT count(*) FROM application_logs
WHERE (?1 IS NULL OR level = ?1)
  AND (?2 IS NULL OR component = ?2)
  AND (?3 IS NULL OR server_id = ?3)
  AND (?4 IS NULL OR request_id = ?4)
  AND (?5 IS NULL OR message LIKE '%' || ?5 || '%')
  AND (?6 IS NULL OR ts >= ?6)
  AND (?7 IS NULL OR ts <= ?7)
`

type CountApplicationLogsParams struct {
	Level     interface{} `json:"level"`
	Component interface{} `json:"component"`
	ServerID  interface{} `json:"server_id"`
	RequestID interface{} `json:"request_id"`
	Search    interface{} `json:"search"`
	FromTs    interface{} `json:"from_ts"`
	ToTs      interface{} `json:"to_ts"`
}

func (q *Queries) CountApplicationLogs(ctx context.Context, arg CountApplicationLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countApplicationLogs,
		arg.Level,
		arg.Component,
		arg.ServerID,
		arg.RequestID,
		arg.Search,
		arg.FromTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditByAction = `-- name: CountAuditByAction :many
SELECT action, count(*) AS count FROM audit_logs
WHERE ts > ?1 GROUP BY action ORDER BY count DESC
`

type CountAuditByActionRow struct {
	Action string `json:"action"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountAuditByAction(ctx context.Context, ts time.Time) ([]CountAuditByActionRow, error) {
	rows, err := q.db.QueryContext(ctx, countAuditByAction, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAuditByActionRow{}
	for rows.Next() {
		var i CountAuditByActionRow
		if err := rows.Scan(&i.Action, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditByResult = `-- name: CountAuditByResult :many
SELECT result, count(*) AS count FROM audit_logs
WHERE ts > ?1 GROUP BY result ORDER BY count DESC
`

type CountAuditByResultRow struct {
	Result string `json:"result"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountAuditByResult(ctx context.Context, ts time.Time) ([]CountAuditByResultRow, error) {
	rows, err := q.db.QueryContext(ctx, countAuditByResult, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAuditByResultRow{}
	for rows.Next() {
		var i CountAuditByResultRow
		if err := rows.Scan(&i.Result, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs
WHERE (?1 IS NULL OR actor_id = ?1)
  AND (?2 IS NULL OR server_id = ?2)
  AND (?3 IS NULL OR action = ?3)
  AND (?4 IS NULL OR result = ?4)
  AND (?5 IS NULL OR ip = ?5)
  AND (?6 IS NULL OR request_id = ?6)
  AND (?7 IS NULL OR ts >= ?7)
  AND (?8 IS NULL OR ts <= ?8)
  AND (?9 IS NULL
       OR action LIKE '%' || ?9 || '%'
       OR target LIKE '%' || ?9 || '%'
       OR actor_name LIKE '%' || ?9 || '%'
       OR server_name LIKE '%' || ?9 || '%')
`

type CountAuditLogsParams struct {
	ActorID   interface{} `json:"actor_id"`
	ServerID  interface{} `json:"server_id"`
	Action    interface{} `json:"action"`
	Result    interface{} `json:"result"`
	Ip        interface{} `json:"ip"`
	RequestID interface{} `json:"request_id"`
	FromTs    interface{} `json:"from_ts"`
	ToTs      interface{} `json:"to_ts"`
	Search    interface{} `json:"search"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogs,
		arg.ActorID,
		arg.ServerID,
		arg.Action,
		arg.Result,
		arg.Ip,
		arg.RequestID,
		arg.FromTs,
		arg.ToTs,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSecurityEvents = `-- name: CountSecurityEvents :one
SELECT count(*) FROM audit_logs
WHERE ts > ?1 AND action IN ('SECURITY_EVENT', 'ACCESS_DENIED', 'LOGIN_FAILED')
`

func (q *Queries) CountSecurityEvents(ctx context.Context, ts time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSecurityEvents, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteApplicationLogsBefore = `-- name: DeleteApplicationLogsBefore :execrows
DELETE FROM application_logs WHERE ts < ?1
`

func (q *Queries) DeleteApplicationLogsBefore(ctx context.Context, ts time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteApplicationLogsBefore, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAuditBefore = `-- name: DeleteAuditBefore :execrows
DELETE FROM audit_logs WHERE ts < ?1
`

// The single permitted deletion path. The caller records an AUDIT_PRUNED
// event so that pruning is itself visible in the trail.
func (q *Queries) DeleteAuditBefore(ctx context.Context, ts time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuditBefore, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT id, ts, actor_id, actor_name, "action", target, server_id, server_name, result, request_id, ip, user_agent, metadata FROM audit_logs WHERE id = ?1
`

func (q *Queries) GetAuditLog(ctx context.Context, id int64) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getAuditLog, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.ActorID,
		&i.ActorName,
		&i.Action,
		&i.Target,
		&i.ServerID,
		&i.ServerName,
		&i.Result,
		&i.RequestID,
		&i.Ip,
		&i.UserAgent,
		&i.Metadata,
	)
	return i, err
}

const insertApplicationLog = `-- name: InsertApplicationLog :one

INSERT INTO application_logs (level, component, message, request_id, actor_id, server_id, fields)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, ts, level, component, message, request_id, actor_id, server_id, fields
`

type InsertApplicationLogParams struct {
	Level     string `json:"level"`
	Component string `json:"component"`
	Message   string `json:"message"`
	RequestID string `json:"request_id"`
	ActorID   *int64 `json:"actor_id"`
	ServerID  *int64 `json:"server_id"`
	Fields    []byte `json:"fields"`
}

// Application logs ------------------------------------------------------------
func (q *Queries) InsertApplicationLog(ctx context.Context, arg InsertApplicationLogParams) (ApplicationLog, error) {
	row := q.db.QueryRowContext(ctx, insertApplicationLog,
		arg.Level,
		arg.Component,
		arg.Message,
		arg.RequestID,
		arg.ActorID,
		arg.ServerID,
		arg.Fields,
	)
	var i ApplicationLog
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.Level,
		&i.Component,
		&i.Message,
		&i.RequestID,
		&i.ActorID,
		&i.ServerID,
		&i.Fields,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one

INSERT INTO audit_logs (actor_id, actor_name, action, target, server_id, server_name,
                        result, request_id, ip, user_agent, metadata)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
RETURNING id, ts, actor_id, actor_name, "action", target, server_id, server_name, result, request_id, ip, user_agent, metadata
`

type InsertAuditLogParams struct {
	ActorID    *int64 `json:"actor_id"`
	ActorName  string `json:"actor_name"`
	Action     string `json:"action"`
	Target     string `json:"target"`
	ServerID   *int64 `json:"server_id"`
	ServerName string `json:"server_name"`
	Result     string `json:"result"`
	RequestID  string `json:"request_id"`
	Ip         string `json:"ip"`
	UserAgent  string `json:"user_agent"`
	Metadata   []byte `json:"metadata"`
}

// Audit log -----------------------------------------------------------------
//
// append-only: these queries only ever INSERT or SELECT. No UPDATE or DELETE
// query exists, which is what makes the trail tamper-resistant through the
// application (Design Spec 27.1). Retention pruning runs through
// DeleteAuditBefore, the single documented exception.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, insertAuditLog,
		arg.ActorID,
		arg.ActorName,
		arg.Action,
		arg.Target,
		arg.ServerID,
		arg.ServerName,
		arg.Result,
		arg.RequestID,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.ActorID,
		&i.ActorName,
		&i.Action,
		&i.Target,
		&i.ServerID,
		&i.ServerName,
		&i.Result,
		&i.RequestID,
		&i.Ip,
		&i.UserAgent,
		&i.Metadata,
	)
	return i, err
}

const listApplicationLogs = `-- name: ListApplicationLogs :many
SELECT id, ts, level, component, message, request_id, actor_id, server_id, fields FROM application_logs
WHERE (?3 IS NULL OR level = ?3)
  AND (?4 IS NULL OR component = ?4)
  AND (?5 IS NULL OR server_id = ?5)
  AND (?6 IS NULL OR request_id = ?6)
  AND (?7 IS NULL OR message LIKE '%' || ?7 || '%')
  AND (?8 IS NULL OR ts >= ?8)
  AND (?9 IS NULL OR ts <= ?9)
ORDER BY ts DESC, id DESC
LIMIT ?1 OFFSET ?2
`

type ListApplicationLogsParams struct {
	Limit     int64       `json:"limit"`
	Offset    int64       `json:"offset"`
	Level     interface{} `json:"level"`
	Component interface{} `json:"component"`
	ServerID  interface{} `json:"server_id"`
	RequestID interface{} `json:"request_id"`
	Search    interface{} `json:"search"`
	FromTs    interface{} `json:"from_ts"`
	ToTs      interface{} `json:"to_ts"`
}

func (q *Queries) ListApplicationLogs(ctx context.Context, arg ListApplicationLogsParams) ([]ApplicationLog, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationLogs,
		arg.Limit,
		arg.Offset,
		arg.Level,
		arg.Component,
		arg.ServerID,
		arg.RequestID,
		arg.Search,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationLog{}
	for rows.Next() {
		var i ApplicationLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Level,
			&i.Component,
			&i.Message,
			&i.RequestID,
			&i.ActorID,
			&i.ServerID,
			&i.Fields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, ts, actor_id, actor_name, "action", target, server_id, server_name, result, request_id, ip, user_agent, metadata FROM audit_logs
WHERE (?3 IS NULL OR actor_id = ?3)
  AND (?4 IS NULL OR server_id = ?4)
  AND (?5 IS NULL OR action = ?5)
  AND (?6 IS NULL OR result = ?6)
  AND (?7 IS NULL OR ip = ?7)
  AND (?8 IS NULL OR request_id = ?8)
  AND (?9 IS NULL OR ts >= ?9)
  AND (?10 IS NULL OR ts <= ?10)
  AND (?11 IS NULL
       OR action LIKE '%' || ?11 || '%'
       OR target LIKE '%' || ?11 || '%'
       OR actor_name LIKE '%' || ?11 || '%'
       OR server_name LIKE '%' || ?11 || '%')
ORDER BY ts DESC, id DESC
LIMIT ?1 OFFSET ?2
`

type ListAuditLogsParams struct {
	Limit     int64       `json:"limit"`
	Offset    int64       `json:"offset"`
	ActorID   interface{} `json:"actor_id"`
	ServerID  interface{} `json:"server_id"`
	Action    interface{} `json:"action"`
	Result    interface{} `json:"result"`
	Ip        interface{} `json:"ip"`
	RequestID interface{} `json:"request_id"`
	FromTs    interface{} `json:"from_ts"`
	ToTs      interface{} `json:"to_ts"`
	Search    interface{} `json:"search"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.ActorID,
		arg.ServerID,
		arg.Action,
		arg.Result,
		arg.Ip,
		arg.RequestID,
		arg.FromTs,
		arg.ToTs,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.Target,
			&i.ServerID,
			&i.ServerName,
			&i.Result,
			&i.RequestID,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAuditForServer = `-- name: ListRecentAuditForServer :many
SELECT id, ts, actor_id, actor_name, "action", target, server_id, server_name, result, request_id, ip, user_agent, metadata FROM audit_logs WHERE server_id = ?1 ORDER BY ts DESC, id DESC LIMIT ?2
`

type ListRecentAuditForServerParams struct {
	ServerID *int64 `json:"server_id"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) ListRecentAuditForServer(ctx context.Context, arg ListRecentAuditForServerParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listRecentAuditForServer, arg.ServerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.Target,
			&i.ServerID,
			&i.ServerName,
			&i.Result,
			&i.RequestID,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
