// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package storesqlite

import (
	"context"
	"time"
)

const aggregateRawTo5m = `-- name: AggregateRawTo5m :many
SELECT
    server_id,
    CAST(?1 AS INTEGER) AS bucket,
    avg(cpu_pct)    AS cpu_avg,
    min(cpu_pct)    AS cpu_min,
    max(cpu_pct)    AS cpu_max,
    avg(mem_used)   AS mem_avg,
    max(mem_used)   AS mem_max,
    avg(swap_used)  AS swap_avg,
    max(swap_used)  AS swap_max,
    avg(load1)      AS load_avg,
    count(*)        AS samples
FROM metric_samples
WHERE ts >= ?2 AND ts < ?3
GROUP BY server_id
`

type AggregateRawTo5mParams struct {
	Column1 int64     `json:"column_1"`
	Ts      time.Time `json:"ts"`
	Ts_2    time.Time `json:"ts_2"`
}

type AggregateRawTo5mRow struct {
	ServerID int64       `json:"server_id"`
	Bucket   int64       `json:"bucket"`
	CpuAvg   *float64    `json:"cpu_avg"`
	CpuMin   interface{} `json:"cpu_min"`
	CpuMax   interface{} `json:"cpu_max"`
	MemAvg   *float64    `json:"mem_avg"`
	MemMax   interface{} `json:"mem_max"`
	SwapAvg  *float64    `json:"swap_avg"`
	SwapMax  interface{} `json:"swap_max"`
	LoadAvg  *float64    `json:"load_avg"`
	Samples  int64       `json:"samples"`
}

// Buckets raw samples into fixed windows. floor() works identically on both
// dialects for integer division of epoch seconds.
func (q *Queries) AggregateRawTo5m(ctx context.Context, arg AggregateRawTo5mParams) ([]AggregateRawTo5mRow, error) {
	rows, err := q.db.QueryContext(ctx, aggregateRawTo5m, arg.Column1, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateRawTo5mRow{}
	for rows.Next() {
		var i AggregateRawTo5mRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Bucket,
			&i.CpuAvg,
			&i.CpuMin,
			&i.CpuMax,
			&i.MemAvg,
			&i.MemMax,
			&i.SwapAvg,
			&i.SwapMax,
			&i.LoadAvg,
			&i.Samples,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMetricSamples = `-- name: CountMetricSamples :one
SELECT count(*) FROM metric_samples WHERE server_id = ?1 AND ts >= ?2 AND ts <= ?3
`

type CountMetricSamplesParams struct {
	ServerID int64     `json:"server_id"`
	Ts       time.Time `json:"ts"`
	Ts_2     time.Time `json:"ts_2"`
}

func (q *Queries) CountMetricSamples(ctx context.Context, arg CountMetricSamplesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMetricSamples, arg.ServerID, arg.Ts, arg.Ts_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMetricAggregatesBefore = `-- name: DeleteMetricAggregatesBefore :execrows
DELETE FROM metric_aggregates WHERE resolution = ?1 AND ts < ?2
`

type DeleteMetricAggregatesBeforeParams struct {
	Resolution string    `json:"resolution"`
	Ts         time.Time `json:"ts"`
}

func (q *Queries) DeleteMetricAggregatesBefore(ctx context.Context, arg DeleteMetricAggregatesBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMetricAggregatesBefore, arg.Resolution, arg.Ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMetricFilesystemsBefore = `-- name: DeleteMetricFilesystemsBefore :execrows
DELETE FROM metric_filesystems WHERE ts < ?1
`

func (q *Queries) DeleteMetricFilesystemsBefore(ctx context.Context, ts time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMetricFilesystemsBefore, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMetricSamplesBefore = `-- name: DeleteMetricSamplesBefore :execrows
DELETE FROM metric_samples WHERE ts < ?1
`

func (q *Queries) DeleteMetricSamplesBefore(ctx context.Context, ts time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMetricSamplesBefore, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMetricSamplesForServerBefore = `-- name: DeleteMetricSamplesForServerBefore :execrows
DELETE FROM metric_samples WHERE server_id = ?1 AND ts < ?2
`

type DeleteMetricSamplesForServerBeforeParams struct {
	ServerID int64     `json:"server_id"`
	Ts       time.Time `json:"ts"`
}

func (q *Queries) DeleteMetricSamplesForServerBefore(ctx context.Context, arg DeleteMetricSamplesForServerBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMetricSamplesForServerBefore, arg.ServerID, arg.Ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestMetricSample = `-- name: GetLatestMetricSample :one
SELECT server_id, ts, cpu_pct, load1, load5, load15, mem_total, mem_used, mem_available, mem_cached, mem_buffers, swap_total, swap_used, net_rx_bytes, net_tx_bytes, disk_read_bytes, disk_write_bytes, uptime_seconds, process_count FROM metric_samples WHERE server_id = ?1 ORDER BY ts DESC LIMIT 1
`

func (q *Queries) GetLatestMetricSample(ctx context.Context, serverID int64) (MetricSample, error) {
	row := q.db.QueryRowContext(ctx, getLatestMetricSample, serverID)
	var i MetricSample
	err := row.Scan(
		&i.ServerID,
		&i.Ts,
		&i.CpuPct,
		&i.Load1,
		&i.Load5,
		&i.Load15,
		&i.MemTotal,
		&i.MemUsed,
		&i.MemAvailable,
		&i.MemCached,
		&i.MemBuffers,
		&i.SwapTotal,
		&i.SwapUsed,
		&i.NetRxBytes,
		&i.NetTxBytes,
		&i.DiskReadBytes,
		&i.DiskWriteBytes,
		&i.UptimeSeconds,
		&i.ProcessCount,
	)
	return i, err
}

const getMetricAggregate = `-- name: GetMetricAggregate :one
SELECT server_id, resolution, ts, cpu_pct_avg, cpu_pct_min, cpu_pct_max, mem_used_avg, mem_used_max, swap_used_avg, swap_used_max, net_rx_rate_avg, net_tx_rate_avg, load1_avg, sample_count FROM metric_aggregates
WHERE server_id = ?1 AND resolution = ?2 AND ts = ?3
`

type GetMetricAggregateParams struct {
	ServerID   int64     `json:"server_id"`
	Resolution string    `json:"resolution"`
	Ts         time.Time `json:"ts"`
}

func (q *Queries) GetMetricAggregate(ctx context.Context, arg GetMetricAggregateParams) (MetricAggregate, error) {
	row := q.db.QueryRowContext(ctx, getMetricAggregate, arg.ServerID, arg.Resolution, arg.Ts)
	var i MetricAggregate
	err := row.Scan(
		&i.ServerID,
		&i.Resolution,
		&i.Ts,
		&i.CpuPctAvg,
		&i.CpuPctMin,
		&i.CpuPctMax,
		&i.MemUsedAvg,
		&i.MemUsedMax,
		&i.SwapUsedAvg,
		&i.SwapUsedMax,
		&i.NetRxRateAvg,
		&i.NetTxRateAvg,
		&i.Load1Avg,
		&i.SampleCount,
	)
	return i, err
}

const getMetricSampleAt = `-- name: GetMetricSampleAt :one
SELECT server_id, ts, cpu_pct, load1, load5, load15, mem_total, mem_used, mem_available, mem_cached, mem_buffers, swap_total, swap_used, net_rx_bytes, net_tx_bytes, disk_read_bytes, disk_write_bytes, uptime_seconds, process_count FROM metric_samples WHERE server_id = ?1 AND ts = ?2
`

type GetMetricSampleAtParams struct {
	ServerID int64     `json:"server_id"`
	Ts       time.Time `json:"ts"`
}

func (q *Queries) GetMetricSampleAt(ctx context.Context, arg GetMetricSampleAtParams) (MetricSample, error) {
	row := q.db.QueryRowContext(ctx, getMetricSampleAt, arg.ServerID, arg.Ts)
	var i MetricSample
	err := row.Scan(
		&i.ServerID,
		&i.Ts,
		&i.CpuPct,
		&i.Load1,
		&i.Load5,
		&i.Load15,
		&i.MemTotal,
		&i.MemUsed,
		&i.MemAvailable,
		&i.MemCached,
		&i.MemBuffers,
		&i.SwapTotal,
		&i.SwapUsed,
		&i.NetRxBytes,
		&i.NetTxBytes,
		&i.DiskReadBytes,
		&i.DiskWriteBytes,
		&i.UptimeSeconds,
		&i.ProcessCount,
	)
	return i, err
}

const listLatestFilesystems = `-- name: ListLatestFilesystems :many
SELECT mf.server_id, mf.ts, mf.mount_point, mf.device, mf.fs_type, mf.total_bytes, mf.used_bytes, mf.avail_bytes, mf.used_pct FROM metric_filesystems mf
JOIN (
    SELECT mount_point AS mp, max(ts) AS mts
    FROM metric_filesystems WHERE metric_filesystems.server_id = ?1
    GROUP BY mount_point
) latest ON latest.mp = mf.mount_point AND latest.mts = mf.ts
WHERE mf.server_id = ?1
ORDER BY mf.mount_point
`

// Current usage per mount point, for the dashboard.
func (q *Queries) ListLatestFilesystems(ctx context.Context, serverID int64) ([]MetricFilesystem, error) {
	rows, err := q.db.QueryContext(ctx, listLatestFilesystems, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricFilesystem{}
	for rows.Next() {
		var i MetricFilesystem
		if err := rows.Scan(
			&i.ServerID,
			&i.Ts,
			&i.MountPoint,
			&i.Device,
			&i.FsType,
			&i.TotalBytes,
			&i.UsedBytes,
			&i.AvailBytes,
			&i.UsedPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestSamplesForAllServers = `-- name: ListLatestSamplesForAllServers :many
SELECT m.server_id, m.ts, m.cpu_pct, m.load1, m.load5, m.load15, m.mem_total, m.mem_used, m.mem_available, m.mem_cached, m.mem_buffers, m.swap_total, m.swap_used, m.net_rx_bytes, m.net_tx_bytes, m.disk_read_bytes, m.disk_write_bytes, m.uptime_seconds, m.process_count FROM metric_samples m
JOIN (SELECT server_id AS sid, max(ts) AS mts FROM metric_samples GROUP BY server_id) x
  ON x.sid = m.server_id AND x.mts = m.ts
ORDER BY m.server_id
`

// Dashboard summary: one row per server, the most recent sample.
func (q *Queries) ListLatestSamplesForAllServers(ctx context.Context) ([]MetricSample, error) {
	rows, err := q.db.QueryContext(ctx, listLatestSamplesForAllServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricSample{}
	for rows.Next() {
		var i MetricSample
		if err := rows.Scan(
			&i.ServerID,
			&i.Ts,
			&i.CpuPct,
			&i.Load1,
			&i.Load5,
			&i.Load15,
			&i.MemTotal,
			&i.MemUsed,
			&i.MemAvailable,
			&i.MemCached,
			&i.MemBuffers,
			&i.SwapTotal,
			&i.SwapUsed,
			&i.NetRxBytes,
			&i.NetTxBytes,
			&i.DiskReadBytes,
			&i.DiskWriteBytes,
			&i.UptimeSeconds,
			&i.ProcessCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricAggregates = `-- name: ListMetricAggregates :many
SELECT server_id, resolution, ts, cpu_pct_avg, cpu_pct_min, cpu_pct_max, mem_used_avg, mem_used_max, swap_used_avg, swap_used_max, net_rx_rate_avg, net_tx_rate_avg, load1_avg, sample_count FROM metric_aggregates
WHERE server_id = ?1 AND resolution = ?2 AND ts >= ?3 AND ts <= ?4
ORDER BY ts
LIMIT ?5
`

type ListMetricAggregatesParams struct {
	ServerID   int64     `json:"server_id"`
	Resolution string    `json:"resolution"`
	Ts         time.Time `json:"ts"`
	Ts_2       time.Time `json:"ts_2"`
	Limit      int64     `json:"limit"`
}

func (q *Queries) ListMetricAggregates(ctx context.Context, arg ListMetricAggregatesParams) ([]MetricAggregate, error) {
	rows, err := q.db.QueryContext(ctx, listMetricAggregates,
		arg.ServerID,
		arg.Resolution,
		arg.Ts,
		arg.Ts_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricAggregate{}
	for rows.Next() {
		var i MetricAggregate
		if err := rows.Scan(
			&i.ServerID,
			&i.Resolution,
			&i.Ts,
			&i.CpuPctAvg,
			&i.CpuPctMin,
			&i.CpuPctMax,
			&i.MemUsedAvg,
			&i.MemUsedMax,
			&i.SwapUsedAvg,
			&i.SwapUsedMax,
			&i.NetRxRateAvg,
			&i.NetTxRateAvg,
			&i.Load1Avg,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricFilesystems = `-- name: ListMetricFilesystems :many
SELECT server_id, ts, mount_point, device, fs_type, total_bytes, used_bytes, avail_bytes, used_pct FROM metric_filesystems
WHERE server_id = ?1 AND ts >= ?2 AND ts <= ?3
ORDER BY ts, mount_point
LIMIT ?4
`

type ListMetricFilesystemsParams struct {
	ServerID int64     `json:"server_id"`
	Ts       time.Time `json:"ts"`
	Ts_2     time.Time `json:"ts_2"`
	Limit    int64     `json:"limit"`
}

func (q *Queries) ListMetricFilesystems(ctx context.Context, arg ListMetricFilesystemsParams) ([]MetricFilesystem, error) {
	rows, err := q.db.QueryContext(ctx, listMetricFilesystems,
		arg.ServerID,
		arg.Ts,
		arg.Ts_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricFilesystem{}
	for rows.Next() {
		var i MetricFilesystem
		if err := rows.Scan(
			&i.ServerID,
			&i.Ts,
			&i.MountPoint,
			&i.Device,
			&i.FsType,
			&i.TotalBytes,
			&i.UsedBytes,
			&i.AvailBytes,
			&i.UsedPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricSamples = `-- name: ListMetricSamples :many
SELECT server_id, ts, cpu_pct, load1, load5, load15, mem_total, mem_used, mem_available, mem_cached, mem_buffers, swap_total, swap_used, net_rx_bytes, net_tx_bytes, disk_read_bytes, disk_write_bytes, uptime_seconds, process_count FROM metric_samples
WHERE server_id = ?1 AND ts >= ?2 AND ts <= ?3
ORDER BY ts
LIMIT ?4
`

type ListMetricSamplesParams struct {
	ServerID int64     `json:"server_id"`
	Ts       time.Time `json:"ts"`
	Ts_2     time.Time `json:"ts_2"`
	Limit    int64     `json:"limit"`
}

func (q *Queries) ListMetricSamples(ctx context.Context, arg ListMetricSamplesParams) ([]MetricSample, error) {
	rows, err := q.db.QueryContext(ctx, listMetricSamples,
		arg.ServerID,
		arg.Ts,
		arg.Ts_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricSample{}
	for rows.Next() {
		var i MetricSample
		if err := rows.Scan(
			&i.ServerID,
			&i.Ts,
			&i.CpuPct,
			&i.Load1,
			&i.Load5,
			&i.Load15,
			&i.MemTotal,
			&i.MemUsed,
			&i.MemAvailable,
			&i.MemCached,
			&i.MemBuffers,
			&i.SwapTotal,
			&i.SwapUsed,
			&i.NetRxBytes,
			&i.NetTxBytes,
			&i.DiskReadBytes,
			&i.DiskWriteBytes,
			&i.UptimeSeconds,
			&i.ProcessCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMetricAggregate = `-- name: UpsertMetricAggregate :exec

INSERT INTO metric_aggregates (
    server_id, resolution, ts,
    cpu_pct_avg, cpu_pct_min, cpu_pct_max,
    mem_used_avg, mem_used_max, swap_used_avg, swap_used_max,
    net_rx_rate_avg, net_tx_rate_avg, load1_avg, sample_count
) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14)
ON CONFLICT (server_id, resolution, ts) DO UPDATE SET
    cpu_pct_avg     = EXCLUDED.cpu_pct_avg,
    cpu_pct_min     = EXCLUDED.cpu_pct_min,
    cpu_pct_max     = EXCLUDED.cpu_pct_max,
    mem_used_avg    = EXCLUDED.mem_used_avg,
    mem_used_max    = EXCLUDED.mem_used_max,
    swap_used_avg   = EXCLUDED.swap_used_avg,
    swap_used_max   = EXCLUDED.swap_used_max,
    net_rx_rate_avg = EXCLUDED.net_rx_rate_avg,
    net_tx_rate_avg = EXCLUDED.net_tx_rate_avg,
    load1_avg       = EXCLUDED.load1_avg,
    sample_count    = EXCLUDED.sample_count
`

type UpsertMetricAggregateParams struct {
	ServerID     int64     `json:"server_id"`
	Resolution   string    `json:"resolution"`
	Ts           time.Time `json:"ts"`
	CpuPctAvg    *float64  `json:"cpu_pct_avg"`
	CpuPctMin    *float64  `json:"cpu_pct_min"`
	CpuPctMax    *float64  `json:"cpu_pct_max"`
	MemUsedAvg   *int64    `json:"mem_used_avg"`
	MemUsedMax   *int64    `json:"mem_used_max"`
	SwapUsedAvg  *int64    `json:"swap_used_avg"`
	SwapUsedMax  *int64    `json:"swap_used_max"`
	NetRxRateAvg *float64  `json:"net_rx_rate_avg"`
	NetTxRateAvg *float64  `json:"net_tx_rate_avg"`
	Load1Avg     *float64  `json:"load1_avg"`
	SampleCount  int64     `json:"sample_count"`
}

// Aggregates -----------------------------------------------------------------
// Idempotent on (server_id, resolution, ts), so re-running an aggregation job
// after a partial failure reproduces the same buckets rather than compounding
// them.
func (q *Queries) UpsertMetricAggregate(ctx context.Context, arg UpsertMetricAggregateParams) error {
	_, err := q.db.ExecContext(ctx, upsertMetricAggregate,
		arg.ServerID,
		arg.Resolution,
		arg.Ts,
		arg.CpuPctAvg,
		arg.CpuPctMin,
		arg.CpuPctMax,
		arg.MemUsedAvg,
		arg.MemUsedMax,
		arg.SwapUsedAvg,
		arg.SwapUsedMax,
		arg.NetRxRateAvg,
		arg.NetTxRateAvg,
		arg.Load1Avg,
		arg.SampleCount,
	)
	return err
}

const upsertMetricFilesystem = `-- name: UpsertMetricFilesystem :exec

INSERT INTO metric_filesystems (
    server_id, ts, mount_point, device, fs_type, total_bytes, used_bytes, avail_bytes, used_pct
) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
ON CONFLICT (server_id, ts, mount_point) DO UPDATE SET
    device      = EXCLUDED.device,
    fs_type     = EXCLUDED.fs_type,
    total_bytes = EXCLUDED.total_bytes,
    used_bytes  = EXCLUDED.used_bytes,
    avail_bytes = EXCLUDED.avail_bytes,
    used_pct    = EXCLUDED.used_pct
`

type UpsertMetricFilesystemParams struct {
	ServerID   int64     `json:"server_id"`
	Ts         time.Time `json:"ts"`
	MountPoint string    `json:"mount_point"`
	Device     string    `json:"device"`
	FsType     string    `json:"fs_type"`
	TotalBytes *int64    `json:"total_bytes"`
	UsedBytes  *int64    `json:"used_bytes"`
	AvailBytes *int64    `json:"avail_bytes"`
	UsedPct    *float64  `json:"used_pct"`
}

// Filesystems ----------------------------------------------------------------
func (q *Queries) UpsertMetricFilesystem(ctx context.Context, arg UpsertMetricFilesystemParams) error {
	_, err := q.db.ExecContext(ctx, upsertMetricFilesystem,
		arg.ServerID,
		arg.Ts,
		arg.MountPoint,
		arg.Device,
		arg.FsType,
		arg.TotalBytes,
		arg.UsedBytes,
		arg.AvailBytes,
		arg.UsedPct,
	)
	return err
}

const upsertMetricSample = `-- name: UpsertMetricSample :exec

INSERT INTO metric_samples (
    server_id, ts, cpu_pct, load1, load5, load15,
    mem_total, mem_used, mem_available, mem_cached, mem_buffers,
    swap_total, swap_used, net_rx_bytes, net_tx_bytes,
    disk_read_bytes, disk_write_bytes, uptime_seconds, process_count
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19
)
ON CONFLICT (server_id, ts) DO UPDATE SET
    cpu_pct          = EXCLUDED.cpu_pct,
    load1            = EXCLUDED.load1,
    load5            = EXCLUDED.load5,
    load15           = EXCLUDED.load15,
    mem_total        = EXCLUDED.mem_total,
    mem_used         = EXCLUDED.mem_used,
    mem_available    = EXCLUDED.mem_available,
    mem_cached       = EXCLUDED.mem_cached,
    mem_buffers      = EXCLUDED.mem_buffers,
    swap_total       = EXCLUDED.swap_total,
    swap_used        = EXCLUDED.swap_used,
    net_rx_bytes     = EXCLUDED.net_rx_bytes,
    net_tx_bytes     = EXCLUDED.net_tx_bytes,
    disk_read_bytes  = EXCLUDED.disk_read_bytes,
    disk_write_bytes = EXCLUDED.disk_write_bytes,
    uptime_seconds   = EXCLUDED.uptime_seconds,
    process_count    = EXCLUDED.process_count
`

type UpsertMetricSampleParams struct {
	ServerID       int64     `json:"server_id"`
	Ts             time.Time `json:"ts"`
	CpuPct         *float64  `json:"cpu_pct"`
	Load1          *float64  `json:"load1"`
	Load5          *float64  `json:"load5"`
	Load15         *float64  `json:"load15"`
	MemTotal       *int64    `json:"mem_total"`
	MemUsed        *int64    `json:"mem_used"`
	MemAvailable   *int64    `json:"mem_available"`
	MemCached      *int64    `json:"mem_cached"`
	MemBuffers     *int64    `json:"mem_buffers"`
	SwapTotal      *int64    `json:"swap_total"`
	SwapUsed       *int64    `json:"swap_used"`
	NetRxBytes     *int64    `json:"net_rx_bytes"`
	NetTxBytes     *int64    `json:"net_tx_bytes"`
	DiskReadBytes  *int64    `json:"disk_read_bytes"`
	DiskWriteBytes *int64    `json:"disk_write_bytes"`
	UptimeSeconds  *int64    `json:"uptime_seconds"`
	ProcessCount   *int64    `json:"process_count"`
}

// Metric samples ------------------------------------------------------------
//
// A NULL column means "not collected", which is distinct from 0. Aggregations
// use AVG/MAX, which ignore NULLs, so an absent metric never drags an average
// toward zero (Design Spec 18.4).
// Idempotent on (server_id, ts): replaying a sample overwrites rather than
// duplicating, so a retried job cannot double-count.
func (q *Queries) UpsertMetricSample(ctx context.Context, arg UpsertMetricSampleParams) error {
	_, err := q.db.ExecContext(ctx, upsertMetricSample,
		arg.ServerID,
		arg.Ts,
		arg.CpuPct,
		arg.Load1,
		arg.Load5,
		arg.Load15,
		arg.MemTotal,
		arg.MemUsed,
		arg.MemAvailable,
		arg.MemCached,
		arg.MemBuffers,
		arg.SwapTotal,
		arg.SwapUsed,
		arg.NetRxBytes,
		arg.NetTxBytes,
		arg.DiskReadBytes,
		arg.DiskWriteBytes,
		arg.UptimeSeconds,
		arg.ProcessCount,
	)
	return err
}
