// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storesqlite

import (
	"time"
)

type ApiToken struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	Name       string    `json:"name"`
	TokenHash  []byte    `json:"token_hash"`
	Scopes     []byte    `json:"scopes"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiresAt  *string   `json:"expires_at"`
	LastUsedAt *string   `json:"last_used_at"`
	RevokedAt  *string   `json:"revoked_at"`
}

type ApplicationLog struct {
	ID        int64     `json:"id"`
	Ts        time.Time `json:"ts"`
	Level     string    `json:"level"`
	Component string    `json:"component"`
	Message   string    `json:"message"`
	RequestID string    `json:"request_id"`
	ActorID   *int64    `json:"actor_id"`
	ServerID  *int64    `json:"server_id"`
	Fields    []byte    `json:"fields"`
}

type AuditLog struct {
	ID         int64     `json:"id"`
	Ts         time.Time `json:"ts"`
	ActorID    *int64    `json:"actor_id"`
	ActorName  string    `json:"actor_name"`
	Action     string    `json:"action"`
	Target     string    `json:"target"`
	ServerID   *int64    `json:"server_id"`
	ServerName string    `json:"server_name"`
	Result     string    `json:"result"`
	RequestID  string    `json:"request_id"`
	Ip         string    `json:"ip"`
	UserAgent  string    `json:"user_agent"`
	Metadata   []byte    `json:"metadata"`
}

type Backup struct {
	ID         int64     `json:"id"`
	Filename   string    `json:"filename"`
	Path       string    `json:"path"`
	SizeBytes  int64     `json:"size_bytes"`
	Checksum   string    `json:"checksum"`
	Status     string    `json:"status"`
	Error      string    `json:"error"`
	StartedAt  time.Time `json:"started_at"`
	FinishedAt *string   `json:"finished_at"`
	CreatedBy  *int64    `json:"created_by"`
}

type Job struct {
	ID          int64     `json:"id"`
	Kind        string    `json:"kind"`
	Status      string    `json:"status"`
	Priority    int64     `json:"priority"`
	Attempts    int64     `json:"attempts"`
	MaxAttempts int64     `json:"max_attempts"`
	RunAt       time.Time `json:"run_at"`
	LockedBy    *string   `json:"locked_by"`
	LockedAt    *string   `json:"locked_at"`
	Payload     []byte    `json:"payload"`
	Progress    float64   `json:"progress"`
	LastError   string    `json:"last_error"`
	CreatedBy   *int64    `json:"created_by"`
	ServerID    *int64    `json:"server_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	FinishedAt  *string   `json:"finished_at"`
	DedupeKey   *string   `json:"dedupe_key"`
}

type LoginHistory struct {
	ID            int64     `json:"id"`
	UserID        *int64    `json:"user_id"`
	Username      string    `json:"username"`
	Ip            string    `json:"ip"`
	UserAgent     string    `json:"user_agent"`
	Success       bool      `json:"success"`
	FailureReason string    `json:"failure_reason"`
	SessionID     string    `json:"session_id"`
	Ts            time.Time `json:"ts"`
}

type MetricAggregate struct {
	ServerID     int64     `json:"server_id"`
	Resolution   string    `json:"resolution"`
	Ts           time.Time `json:"ts"`
	CpuPctAvg    *float64  `json:"cpu_pct_avg"`
	CpuPctMin    *float64  `json:"cpu_pct_min"`
	CpuPctMax    *float64  `json:"cpu_pct_max"`
	MemUsedAvg   *int64    `json:"mem_used_avg"`
	MemUsedMax   *int64    `json:"mem_used_max"`
	SwapUsedAvg  *int64    `json:"swap_used_avg"`
	SwapUsedMax  *int64    `json:"swap_used_max"`
	NetRxRateAvg *float64  `json:"net_rx_rate_avg"`
	NetTxRateAvg *float64  `json:"net_tx_rate_avg"`
	Load1Avg     *float64  `json:"load1_avg"`
	SampleCount  int64     `json:"sample_count"`
}

type MetricFilesystem struct {
	ServerID   int64     `json:"server_id"`
	Ts         time.Time `json:"ts"`
	MountPoint string    `json:"mount_point"`
	Device     string    `json:"device"`
	FsType     string    `json:"fs_type"`
	TotalBytes *int64    `json:"total_bytes"`
	UsedBytes  *int64    `json:"used_bytes"`
	AvailBytes *int64    `json:"avail_bytes"`
	UsedPct    *float64  `json:"used_pct"`
}

type MetricSample struct {
	ServerID       int64     `json:"server_id"`
	Ts             time.Time `json:"ts"`
	CpuPct         *float64  `json:"cpu_pct"`
	Load1          *float64  `json:"load1"`
	Load5          *float64  `json:"load5"`
	Load15         *float64  `json:"load15"`
	MemTotal       *int64    `json:"mem_total"`
	MemUsed        *int64    `json:"mem_used"`
	MemAvailable   *int64    `json:"mem_available"`
	MemCached      *int64    `json:"mem_cached"`
	MemBuffers     *int64    `json:"mem_buffers"`
	SwapTotal      *int64    `json:"swap_total"`
	SwapUsed       *int64    `json:"swap_used"`
	NetRxBytes     *int64    `json:"net_rx_bytes"`
	NetTxBytes     *int64    `json:"net_tx_bytes"`
	DiskReadBytes  *int64    `json:"disk_read_bytes"`
	DiskWriteBytes *int64    `json:"disk_write_bytes"`
	UptimeSeconds  *int64    `json:"uptime_seconds"`
	ProcessCount   *int64    `json:"process_count"`
}

type Notification struct {
	ID        int64     `json:"id"`
	Ts        time.Time `json:"ts"`
	Kind      string    `json:"kind"`
	Severity  string    `json:"severity"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	ServerID  *int64    `json:"server_id"`
	DedupeKey string    `json:"dedupe_key"`
	IsRead    bool      `json:"is_read"`
	CreatedAt time.Time `json:"created_at"`
}

type NotificationChannel struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	Config    []byte    `json:"config"`
	IsEnabled bool      `json:"is_enabled"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Permission struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Role struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RolePermission struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type Server struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	TargetType    string    `json:"target_type"`
	Host          string    `json:"host"`
	Port          int64     `json:"port"`
	Username      string    `json:"username"`
	AuthMethod    string    `json:"auth_method"`
	HostKeyPolicy string    `json:"host_key_policy"`
	Tags          []byte    `json:"tags"`
	Notes         string    `json:"notes"`
	IsFavourite   bool      `json:"is_favourite"`
	Status        string    `json:"status"`
	StatusDetail  string    `json:"status_detail"`
	Os            string    `json:"os"`
	Kernel        string    `json:"kernel"`
	Arch          string    `json:"arch"`
	LastSeenAt    *string   `json:"last_seen_at"`
	LastErrorAt   *string   `json:"last_error_at"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Version       int64     `json:"version"`
}

type ServerCredential struct {
	ID         int64     `json:"id"`
	ServerID   int64     `json:"server_id"`
	Kind       string    `json:"kind"`
	Ciphertext []byte    `json:"ciphertext"`
	Version    int64     `json:"version"`
	CreatedAt  time.Time `json:"created_at"`
	RotatedAt  *string   `json:"rotated_at"`
}

type ServerHostKey struct {
	ID          int64     `json:"id"`
	ServerID    int64     `json:"server_id"`
	Algorithm   string    `json:"algorithm"`
	Fingerprint string    `json:"fingerprint"`
	PublicKey   []byte    `json:"public_key"`
	State       string    `json:"state"`
	FirstSeen   time.Time `json:"first_seen"`
	TrustedAt   *string   `json:"trusted_at"`
	TrustedBy   *int64    `json:"trusted_by"`
}

type ServerPermission struct {
	UserID       int64     `json:"user_id"`
	ServerID     int64     `json:"server_id"`
	PermissionID int64     `json:"permission_id"`
	GrantedAt    time.Time `json:"granted_at"`
	GrantedBy    *int64    `json:"granted_by"`
}

type ServerTag struct {
	ServerID int64 `json:"server_id"`
	TagID    int64 `json:"tag_id"`
}

type Session struct {
	ID         string    `json:"id"`
	UserID     int64     `json:"user_id"`
	TokenHash  []byte    `json:"token_hash"`
	Ip         string    `json:"ip"`
	UserAgent  string    `json:"user_agent"`
	CreatedAt  time.Time `json:"created_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
	ExpiresAt  time.Time `json:"expires_at"`
	RevokedAt  *string   `json:"revoked_at"`
}

type Setting struct {
	Key       string    `json:"key"`
	Value     []byte    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
	UpdatedBy *int64    `json:"updated_by"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type TerminalSession struct {
	ID          string    `json:"id"`
	UserID      int64     `json:"user_id"`
	ServerID    int64     `json:"server_id"`
	SessionID   string    `json:"session_id"`
	Cols        int64     `json:"cols"`
	Rows        int64     `json:"rows"`
	OpenedAt    time.Time `json:"opened_at"`
	ClosedAt    *string   `json:"closed_at"`
	CloseReason string    `json:"close_reason"`
}

type User struct {
	ID                 int64     `json:"id"`
	Username           string    `json:"username"`
	PasswordHash       string    `json:"password_hash"`
	DisplayName        string    `json:"display_name"`
	IsActive           bool      `json:"is_active"`
	IsBootstrapDefault bool      `json:"is_bootstrap_default"`
	MustChangePassword bool      `json:"must_change_password"`
	LastLoginAt        *string   `json:"last_login_at"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	DeletedAt          *string   `json:"deleted_at"`
	Version            int64     `json:"version"`
}

type UserRole struct {
	UserID    int64     `json:"user_id"`
	RoleID    int64     `json:"role_id"`
	GrantedAt time.Time `json:"granted_at"`
}
