// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package storesqlite

import (
	"context"
	"time"
)

const countActiveSessions = `-- name: CountActiveSessions :one
SELECT count(*) FROM sessions WHERE revoked_at IS NULL AND expires_at > strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

func (q *Queries) CountActiveSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLoginHistory = `-- name: CountLoginHistory :one
SELECT count(*) FROM login_history
WHERE (?1 IS NULL OR user_id = ?1)
  AND (?2 IS NULL OR ip = ?2)
  AND (?3 IS NULL OR success = ?3)
  AND (?4 IS NULL OR ts >= ?4)
  AND (?5 IS NULL OR ts <= ?5)
`

type CountLoginHistoryParams struct {
	UserID  interface{} `json:"user_id"`
	Ip      interface{} `json:"ip"`
	Success interface{} `json:"success"`
	FromTs  interface{} `json:"from_ts"`
	ToTs    interface{} `json:"to_ts"`
}

func (q *Queries) CountLoginHistory(ctx context.Context, arg CountLoginHistoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLoginHistory,
		arg.UserID,
		arg.Ip,
		arg.Success,
		arg.FromTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentLoginFailures = `-- name: CountRecentLoginFailures :one
SELECT count(*) FROM login_history
WHERE username = ?1 AND success = 0 AND ts > ?2
`

type CountRecentLoginFailuresParams struct {
	Username string    `json:"username"`
	Ts       time.Time `json:"ts"`
}

// Counts recent failures for one account, used by the progressive-lockout
// check. Deliberately independent of the IP-based limiter.
func (q *Queries) CountRecentLoginFailures(ctx context.Context, arg CountRecentLoginFailuresParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentLoginFailures, arg.Username, arg.Ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentLoginFailuresByIP = `-- name: CountRecentLoginFailuresByIP :one
SELECT count(*) FROM login_history
WHERE ip = ?1 AND success = 0 AND ts > ?2
`

type CountRecentLoginFailuresByIPParams struct {
	Ip string    `json:"ip"`
	Ts time.Time `json:"ts"`
}

func (q *Queries) CountRecentLoginFailuresByIP(ctx context.Context, arg CountRecentLoginFailuresByIPParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentLoginFailuresByIP, arg.Ip, arg.Ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (id, user_id, token_hash, ip, user_agent, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING id, user_id, token_hash, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at, reauth_at
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	UserID    int64     `json:"user_id"`
	TokenHash []byte    `json:"token_hash"`
	Ip        string    `json:"ip"`
	UserAgent string    `json:"user_agent"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Sessions ------------------------------------------------------------------
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Ip,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReauthAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= ?1 OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLoginHistoryBefore = `-- name: DeleteLoginHistoryBefore :execrows
DELETE FROM login_history WHERE ts < ?1
`

func (q *Queries) DeleteLoginHistoryBefore(ctx context.Context, ts time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLoginHistoryBefore, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, token_hash, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at, reauth_at FROM sessions WHERE id = ?1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReauthAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at, reauth_at FROM sessions
WHERE token_hash = ?1 AND revoked_at IS NULL AND expires_at > strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

// Lookup is by token hash: the raw token is never stored, so a database leak
// does not yield usable session tokens.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReauthAt,
	)
	return i, err
}

const insertLoginHistory = `-- name: InsertLoginHistory :one

INSERT INTO login_history (user_id, username, ip, user_agent, success, failure_reason, session_id)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, user_id, username, ip, user_agent, success, failure_reason, session_id, ts
`

type InsertLoginHistoryParams struct {
	UserID        *int64 `json:"user_id"`
	Username      string `json:"username"`
	Ip            string `json:"ip"`
	UserAgent     string `json:"user_agent"`
	Success       bool   `json:"success"`
	FailureReason string `json:"failure_reason"`
	SessionID     string `json:"session_id"`
}

// Login history --------------------------------------------------------------
func (q *Queries) InsertLoginHistory(ctx context.Context, arg InsertLoginHistoryParams) (LoginHistory, error) {
	row := q.db.QueryRowContext(ctx, insertLoginHistory,
		arg.UserID,
		arg.Username,
		arg.Ip,
		arg.UserAgent,
		arg.Success,
		arg.FailureReason,
		arg.SessionID,
	)
	var i LoginHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Ip,
		&i.UserAgent,
		&i.Success,
		&i.FailureReason,
		&i.SessionID,
		&i.Ts,
	)
	return i, err
}

const listAllSessions = `-- name: ListAllSessions :many
SELECT s.id, s.user_id, s.token_hash, s.ip, s.user_agent, s.created_at, s.last_seen_at, s.expires_at, s.revoked_at, s.reauth_at, u.username FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.revoked_at IS NULL AND s.expires_at > strftime('%Y-%m-%dT%H:%M:%fZ','now')
ORDER BY s.last_seen_at DESC
LIMIT ?1 OFFSET ?2
`

type ListAllSessionsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListAllSessionsRow struct {
	ID         string    `json:"id"`
	UserID     int64     `json:"user_id"`
	TokenHash  []byte    `json:"token_hash"`
	Ip         string    `json:"ip"`
	UserAgent  string    `json:"user_agent"`
	CreatedAt  time.Time `json:"created_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
	ExpiresAt  time.Time `json:"expires_at"`
	RevokedAt  *string   `json:"revoked_at"`
	ReauthAt   *string   `json:"reauth_at"`
	Username   string    `json:"username"`
}

func (q *Queries) ListAllSessions(ctx context.Context, arg ListAllSessionsParams) ([]ListAllSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSessions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSessionsRow{}
	for rows.Next() {
		var i ListAllSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ReauthAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoginHistory = `-- name: ListLoginHistory :many
SELECT id, user_id, username, ip, user_agent, success, failure_reason, session_id, ts FROM login_history
WHERE (?3 IS NULL OR user_id = ?3)
  AND (?4 IS NULL OR ip = ?4)
  AND (?5 IS NULL OR success = ?5)
  AND (?6 IS NULL OR ts >= ?6)
  AND (?7 IS NULL OR ts <= ?7)
ORDER BY ts DESC, id DESC
LIMIT ?1 OFFSET ?2
`

type ListLoginHistoryParams struct {
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
	UserID  interface{} `json:"user_id"`
	Ip      interface{} `json:"ip"`
	Success interface{} `json:"success"`
	FromTs  interface{} `json:"from_ts"`
	ToTs    interface{} `json:"to_ts"`
}

func (q *Queries) ListLoginHistory(ctx context.Context, arg ListLoginHistoryParams) ([]LoginHistory, error) {
	rows, err := q.db.QueryContext(ctx, listLoginHistory,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.Ip,
		arg.Success,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginHistory{}
	for rows.Next() {
		var i LoginHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Ip,
			&i.UserAgent,
			&i.Success,
			&i.FailureReason,
			&i.SessionID,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, token_hash, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at, reauth_at FROM sessions
WHERE user_id = ?1 AND revoked_at IS NULL AND expires_at > strftime('%Y-%m-%dT%H:%M:%fZ','now')
ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ReauthAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ?1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeSession, id)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :execrows
UPDATE sessions SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE user_id = ?1 AND revoked_at IS NULL
`

// Revoking every other session is part of changing a password.
func (q *Queries) RevokeUserSessions(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUserSessionsExcept = `-- name: RevokeUserSessionsExcept :execrows
UPDATE sessions SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE user_id = ?1 AND id <> ?2 AND revoked_at IS NULL
`

type RevokeUserSessionsExceptParams struct {
	UserID int64  `json:"user_id"`
	ID     string `json:"id"`
}

func (q *Queries) RevokeUserSessionsExcept(ctx context.Context, arg RevokeUserSessionsExceptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUserSessionsExcept, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSessionReauthAt = `-- name: SetSessionReauthAt :exec
UPDATE sessions SET reauth_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ?1
`

// Records a fresh password confirmation for the re-authentication window
// (Design Spec section 13.3).
func (q *Queries) SetSessionReauthAt(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setSessionReauthAt, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ?1
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchSession, id)
	return err
}
